[WiP] feat: new & accessible colours
transferwise/neptune-web pull request #1089
Opened 2021-08-10 16:29 UTC by dozortsev

## 🖼 Context

## 🚀 Changes

 

## 🤔 Considerations

## ✅ Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [ ] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2021-09-20 12:58 UTC, dozortsev commented on packages/css/src/less/addons/_background-utilities.less
> +.bg-neutral,
see these docs about this utility classes here https://transferwise.github.io/neptune-web/branch/accessible-colours/styles/addons/BackgroundUtilities

2021-09-20 12:59 UTC, dozortsev commented on packages/css/src/less/badge.less
> +.badge {
copied from Bootstrap

2021-09-20 13:00 UTC, dozortsev commented on packages/css/src/less/breadcrumbs.less
> +
copied from Bootstrap in order to adjust colors

2021-09-20 13:01 UTC, dozortsev commented on packages/css/src/less/close.less
> +.close {
copied from Bootstrap in order to adjust colors

2021-09-20 13:02 UTC, dozortsev commented on packages/css/src/less/dropdowns.less
> +@import (reference) '../variables/legacy-variables.less';
copied from Bootstrap in order to adjust colors

2021-09-20 14:04 UTC, dozortsev commented on packages/docs/pages/about/Styles.mdx
rendered https://transferwise.github.io/neptune-web/branch/accessible-colours/about/Styles

2021-09-20 14:04 UTC, dozortsev commented on packages/docs/pages/styles/addons/BackgroundUtilities.mdx
> +import { Link } from '@transferwise/components';
rendered https://transferwise.github.io/neptune-web/branch/accessible-colours/styles/addons/BackgroundUtilities

2021-09-20 14:05 UTC, dozortsev commented on packages/docs/pages/styles/tokens/Colors.tsx
> +import { Link } from '@transferwise/components';
rendered https://transferwise.github.io/neptune-web/branch/accessible-colours/styles/tokens/Colors

2021-09-23 08:50 UTC, gusso requested changes
Almost totally perfect, just a couple of changes I suggested ⚡️

2021-09-23 08:50 UTC, gusso commented on packages/docs/public/static/assets/main.css
> +  background: var(--color-base-navy-mid);
```suggestion
  background: var(--color-base-navy-light);
```

2021-09-23 08:50 UTC, gusso commented on packages/docs/public/static/assets/main.css
> +  color: var(--color-content-secondary);
```suggestion
  color: var(--color-base-smoke-mid);
```

2021-09-23 08:50 UTC, gusso commented on packages/docs/public/static/assets/main.css
This background colour is causing 2 background neutrals to be overlapped and making the sidebar darker, we can probably remove this one.

2021-09-23 08:50 UTC, gusso commented on packages/components/src/chip/Chip.less
> +  background: var(--color-interactive-secondary);
```suggestion
  background: var(--color-background-neutral);
```

2021-09-23 09:32 UTC, dozortsev commented on packages/docs/public/static/assets/main.css
🆗

2021-09-23 09:56 UTC, gusso approved these changes

2021-09-23 15:56 UTC, merged