feat: new Progress indicator component
transferwise/neptune-web pull request #1383
Opened 2022-03-30 09:44 UTC by andreapiras

## 🖼 Context

This PR introduces the Progress indicator component
![image](https://user-images.githubusercontent.com/16908937/160800472-52bf9629-e99c-4377-a214-808bc2e3215b.png)

## 🚀 Changes

 
- Introduced Progress indicator

## 🤔 Considerations

## ✅ Checklist

- [x] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [x] Changes are tested and all tests pass
- [x] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [x] Changes work in all supported browsers (don't forget IE11)
- [x] You've updated the documentation if necessary

2022-03-30 09:47 UTC, helendurranttw commented
Hello! Could we not call this progress indicator please? I think progress indicators are more broadly recognised as things that show progress, like [this](https://mui.com/components/progress/#linear).

I know this component is also used to show limits, where the name progress indicator is less relevant. I don't have any immediate ideas but happy to help ideate.

2022-03-31 09:58 UTC, richardmccartney requested changes
I have made some comments regarding the markup and out put of the component 👍 .

2022-03-31 09:58 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.tsx
> +    <div className={classNames('np-progress-indicator', className)}>
We should be ensuring the name of the component corresponds to the name of any CSS classes we have within. As we have named this `ProgressBar` can we change any classes to also follow `np-progress-bar` + child classes?

2022-03-31 09:58 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.tsx
> +        />
There is a concern here we are creating a lot of `div` soup. We should be looking at using the `<progress />` HTML element here. This would give us the ability to use clear and clean mark up.

A suggestion we could follow is a simpler format:

```html
<div className='np-progress'>
  <label htmlFor={id} className='np-progress-label>
    {label}
    {description && <span className="small">{description}</span>}
  </label>
  <progress className="np-progress-indicator__bar" id={id} max={maxValue} value={value}>{value}%</progress>
  <p className="np-progress-indicator__value d-flex justify-content-end h4">{value}</p>
</div>
```

Additional to this, we can add on `aria` attributes that are missing on this component. 

```html
    aria-valuemin="0" 
    aria-valuenow="42" 
    aria-valuemax="100" 
```

2022-03-31 09:58 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.less
> +  &__title {
Can we change this to be `&__label` as title wouldn't reflect the type of HTML element it is styling.

2022-03-31 09:58 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.less
> +  &__bar {
Refactoring the HTML of this component would mean we can use the HTML5 selectors to style the. component. We should be able to style the component with the following selectors. Also we would be able to remove the `&__content` and `&--accent` styles simplifying this CSS.

```css
progress {
/* style rules */
}
progress::-webkit-progress-bar {
/* style rules */
}
progress::-webkit-progress-value {
/* style rules */
}
progress::-moz-progress-bar {
  /* style rules */
}
```

2022-03-31 09:58 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.tsx
> +  title: string;
Can we change this to be `label` in stead of `title` to match the suggested markup changes.

2022-03-31 09:58 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.tsx
> +  progress: string;
Can we change this to be a `number` type instead of `string`?

2022-03-31 09:58 UTC, richardmccartney commented on packages/docs/liveEditorCode/progressBar.code.js
> +<ProgressIndicator
We have called this `<ProgressIndicator />` when the component is called `<ProgressBar />` ?

2022-03-31 10:02 UTC, richardmccartney commented
> Hello! Could we not call this progress indicator please? I think progress indicators are more broadly recognised as things that show progress, like [this](https://mui.com/components/progress/#linear).
> 
> I know this component is also used to show limits, where the name progress indicator is less relevant. I don't have any immediate ideas but happy to help ideate.

@helendurranttw we should look at a loading progress bar to probably be a separate component if we need it or just other general progress/meter components that we need, as a general progress bar and as long as we use the correct semantic markup this would be sufficient.

2022-03-31 13:25 UTC, andreapiras commented on packages/components/src/progressBar/ProgressBar.tsx
> +        />
Where should the aria go? 
aria-valuemin="0" 
aria-valuenow="42" 
aria-valuemax="100"

2022-03-31 14:58 UTC, andreapiras commented on packages/components/src/progressBar/ProgressBar.tsx
> +        />
Do we need maxValue? Should that always be 100?

2022-04-04 12:51 UTC, andreapiras commented on packages/components/src/spendingLimits/SpendingLimits.tsx
> +  progress,
Should default values be set for non required props?

2022-04-04 12:52 UTC, andreapiras commented on packages/components/src/spendingLimits/SpendingLimits.tsx
> +  id: string;
There are other components that uses id. Maybe as a library neptune should have a uniqueId generator?
WDYT?

2022-04-04 13:25 UTC, richardmccartney commented on packages/components/src/spendingLimits/SpendingLimits.tsx
> +  id: string;
Yeah, I like that idea. even if we have shared hooks across the project that would be ideal.

2022-04-05 10:29 UTC, richardmccartney approved these changes

2022-04-05 12:35 UTC, richardmccartney commented
BETA release is now live, `@transferwise/components@40.5.1-beta-ef5ed37487.4+ef5ed37487` if we could test this in any app's that we're to be working with @andreapiras. Then can we just get the final sign off from @transferwise/design-system-designers or @StephanieTW on the interactions and we can merge and organise a release 👍

2022-04-05 14:10 UTC, StephanieTW requested changes
Woohoo looks great!🎉

Just a couple of tiny things:
• Naming: I thought we were still calling the overall component Progress Bar not Spending Limit as it might not always be used for limits?
• Text end should be Body 2 emphasis, not Title 4
• The grey in progress should be Base/Smoke/Light — maybe it is, couldn't work out how to see the colour in the inspector, just looked lighter on my screen.
• There should be 8px padding between the description and progress bar. (4px is correct everywhere else)
• Horizontal padding to the left and right of the component should be 16px.

2022-04-07 15:17 UTC, dozortsev commented on packages/docs/pages/components/internal/Progress.mdx
> +  name: 'Progress',
```suggestion
  name: 'Progress',
  badge: {
    type: 'new',
    expiryDate: '2021-05-02',
  },
--
223 | badge: {
224 | type: 'new',
225 | expiryDate: '2022-01-31',
226 | },


```

2022-04-07 15:17 UTC, dozortsev commented on packages/docs/pages/components/progress/SpendingLimit.mdx
> +  name: 'SpendingLimit',
```suggestion
  name: 'SpendingLimit',
  badge: {
    type: 'new',
    expiryDate: '2021-05-02',
  },
```

2022-04-12 11:58 UTC, richardmccartney commented on packages/docs/pages/components/progress/ProgressBar.mdx
> +  name: 'ProgressBar',
```suggestion
  name: 'ProgressBar',
  badge: {
    type: 'new',
    expiryDate: '2021-05-02',
  },
```

2022-04-12 11:59 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.less
> +.np-spending-limit {
```suggestion
.np-progress-bar {
```

2022-04-12 11:59 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.story.js
> +    id="spending-limit-id"
```suggestion
    id="progress-bar-id"
```

2022-04-12 12:00 UTC, richardmccartney commented on packages/components/src/progressBar/ProgressBar.tsx
> +      <label className="np-spending-limit__title" htmlFor={id}>
```suggestion
      <label className="np-progress-bar__title" htmlFor={id}>
```

2022-04-12 12:01 UTC, richardmccartney commented on packages/docs/liveEditorCode/progressBar.code.js
> +  id="spending-limit-id"
```suggestion
  id="progress-bar-id"
```

2022-04-12 12:02 UTC, richardmccartney reviewed
Last few suggestions and this will be good to go 👍

2022-04-13 09:10 UTC, richardmccartney approved these changes

2022-04-19 12:11 UTC, dozortsev requested changes

2022-04-19 12:11 UTC, dozortsev commented on stylelint.config.js
> +  plugins: ['stylelint-value-no-unknown-custom-properties'],
@richardmccartney I see there build error related to linting but why fixing this by removing this plugin?

2022-04-20 12:36 UTC, dozortsev commented on stylelint.config.js
> +  plugins: ['stylelint-value-no-unknown-custom-properties'],
please remove these fixes from this PR, here is proper fix https://github.com/transferwise/neptune-web/pull/1403

2022-04-21 11:48 UTC, StephanieTW approved these changes

2022-04-21 11:50 UTC, dozortsev approved these changes

2022-04-21 11:51 UTC, merged