Vux 1582 generic dfv2v3 adapter
transferwise/neptune-web pull request #1424
Opened 2022-05-03 15:37 UTC by richardbata

## Context

## Changes

 

## Considerations / Results

## Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [ ] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2022-05-03 16:09 UTC, dozortsev requested changes

2022-05-03 16:09 UTC, dozortsev commented on packages/dynamic-flows/package.json
> +    "angular": "~1.5.10",
I don't think we want bring angular dependecy to neptune-web repo, why this angular 2 react mapping can't be done on consumer side of DF components?

2022-05-04 11:02 UTC, pterblgh commented on packages/dynamic-flows/package.json
> +    "angular": "~1.5.10",
If you want to expose a React component that teams can "just import" then the only way forward is to convert the existing AngularJs based component to a React one in a library. Pushing all the logic to consumers about "How to convert AngularJs to React?" would only result in code-duplication all over the places where Dynamic Flows is used in React consumers IMO.

2022-05-04 13:40 UTC, richardbata commented on packages/dynamic-flows/package.json
> +    "angular": "~1.5.10",
But these are only devDependencies for the Storybook 👍

2022-05-04 14:38 UTC, dozortsev commented on packages/dynamic-flows/package.json
> +    "angular": "~1.5.10",
yeah but it still a dependency, and it needs to be maintained, version needs to be occasionally updated, to fix some conflicts in deps or solve security vulnerability

2022-05-04 14:40 UTC, dozortsev commented on packages/dynamic-flows/package.json
> +    "angular": "~1.5.10",
I would place this demo in https://github.com/transferwise/verification-components

2022-05-09 09:42 UTC, richardbata commented on packages/dynamic-flows/src/adapter/client/v2.tsx
> +  const apiUrl = Dfv2Client.props.apiUrl; // TODO taking from props is risky
Is it safe to take values off props here? If not, what alternatives are there??

2022-05-09 09:42 UTC, richardbata commented on packages/dynamic-flows/src/adapter/client/v2.tsx
> +      // return this.$http(request).then((response) => response.data);
Safe to not use $http?

2022-05-09 09:43 UTC, richardbata commented on packages/dynamic-flows/src/adapter/typings.ts
> +export interface DFv2v3AdapterProps {
Any tips on how to make types better?

2022-05-10 13:53 UTC, pterblgh commented on packages/dynamic-flows/src/adapter/DFv2v3Adapter.tsx
> +const DFv2v3Adapter: ComponentType<DFv2v3AdapterProps> = ({ flowUrl, Dfv3Client, Dfv2Client }) => {
```suggestion
const DFv2v3Adapter: VFC<DFv2v3AdapterProps> = ({ flowUrl, Dfv3Client, Dfv2Client }) => {
```

2022-05-10 13:53 UTC, pterblgh commented on packages/dynamic-flows/src/adapter/DFv2v3Adapter.tsx
> +  );
Can this be encapsulated with the memoized hook that produces`MyDfv2Client`?

2022-05-10 13:53 UTC, pterblgh commented on packages/dynamic-flows/src/adapter/client/utils.ts
> +};
Let's investigate whether we can use the "platform": https://developer.mozilla.org/en-US/docs/Web/API/Headers

2022-05-10 13:53 UTC, pterblgh commented on packages/dynamic-flows/src/adapter/client/utils.ts
> +};
Why do we need these methods? According to the proposal the API endpoint will always return what is the version of the currently returned flow.

2022-05-10 13:53 UTC, pterblgh commented on packages/dynamic-flows/src/adapter/client/utils.ts
> +  }
Error handling is probably missing.

2022-05-10 13:53 UTC, pterblgh commented on packages/dynamic-flows/src/adapter/client/v2.tsx
> +  const apiUrl = Dfv2Client.props.apiUrl; // TODO taking from props is risky
DfV2Client should not have any props, it's just going to be a function reference to a React component that's capable of rendering V2 flows isn't it? 

I would mark every necessary property form the consumer of the component to be able to create a HTTP client. 

According [to this discussion](https://transferwise.slack.com/archives/C2SGDKP4Y/p1650547825683819) we should use `@transferwise/service-comms`

2022-05-10 13:53 UTC, pterblgh commented on packages/dynamic-flows/src/adapter/client/v2.tsx
> +      // return this.$http(request).then((response) => response.data);
Need to check the error handling in `verification-components` - IIRC the AngularJs component expects a `$http` style error object to be able to show error messages (validation, error messages from the server).

2022-05-16 09:22 UTC, richardbata commented on packages/dynamic-flows/src/adapter/client/v2.tsx
> +      // return this.$http(request).then((response) => response.data);
What I am trying to achieve is that the DFv_Clients can keep the ability to have their own HttpClient, which the Adapter/Orchestrator would only extend, not completely replace.

2022-05-16 09:27 UTC, richardbata commented on packages/dynamic-flows/src/adapter/client/v2.tsx
> +  const apiUrl = Dfv2Client.props.apiUrl; // TODO taking from props is risky
What I am trying to achieve is that the DFv_Clients can keep the ability to have their own HttpClient, which the Adapter/Orchestrator would only extend, not completely override.

2022-05-16 12:26 UTC, richardbata commented on packages/dynamic-flows/src/adapter/client/v2.tsx
> +  const apiUrl = Dfv2Client.props.apiUrl; // TODO taking from props is risky
Actually, DFv3Client will be a React component already created, not a function. This is so the consumer of the Orchestrator can initialize the DF client with options it wants to

2022-05-16 12:37 UTC, richardbata commented on packages/dynamic-flows/src/adapter/client/v2.tsx
> +      // return this.$http(request).then((response) => response.data);
I think all that is shown on the UI is an alert at the top, which takes an Error object to display
error-section: https://github.com/transferwise/verification-components/blob/master/src/components/error-section/error-section.html

2022-05-30 13:04 UTC, dozortsev commented on packages/dynamic-flows-version-orchestrator/package.json
> +  "description": "Wise Dynamic Flows in Multiple Versions",
why we need this package? what it does?

2022-05-31 14:29 UTC, dozortsev commented on packages/dynamic-flows-version-orchestrator/docs/version_orchestrator.md
> +platforms.
this repository is open source, you shouldn't mention/expose links to Wise internal docs

2022-05-31 14:35 UTC, JulianG-TW commented on packages/dynamic-flows-version-orchestrator/package.json
> +  "description": "Wise Dynamic Flows in Multiple Versions",
We discussed this in DFv3 Guild meeting. 

Considering that:
- The `dynamic-flows` package only knows about v3.
- Only a few crab apps need transitioning from V2 to V3 flow steps

We decided to have this orchestrator on a separate package so that only those who needed will add the dependency.

2022-05-31 14:52 UTC, JulianG-TW commented on packages/dynamic-flows-version-orchestrator/package.json
> +  "description": "Wise Dynamic Flows in Multiple Versions",
> by v2 you mean https://github.com/transferwise/verification-components right?

yes

> how @transferwise/dynamic-flows-version-orchestrator know about v2?

There's a `DynamicFlowV2Wrapper` component. There's no dependency AFAIK, but there's awareness of a v2.

2022-05-31 15:10 UTC, dozortsev commented on packages/dynamic-flows-version-orchestrator/package.json
> +  "description": "Wise Dynamic Flows in Multiple Versions",
I don't see why `DynamicFlowV2Wrapper` can't live `@transferwise/dynamic-flows`

2022-05-31 15:14 UTC, dozortsev commented on packages/dynamic-flows-version-orchestrator/package.json
> +  "description": "Wise Dynamic Flows in Multiple Versions",
the login in `@transferwise/dynamic-flows-version-orchestrator` looks like an abstraction over V2 and V3 but IMHO it's totally fine to keep it `@transferwise/dynamic-flows`, this way you eventually kill it faster

creating a separate package in this monorepo is a very big maintenance cost

2022-06-02 07:13 UTC, closed without merging