feat(Button): expose `ref` prop
transferwise/neptune-web pull request #1446
Opened 2022-05-11 14:20 UTC by dozortsev

## Context

## Changes

 

## Considerations / Results

## Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [ ] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2022-05-11 14:23 UTC, dozortsev commented on packages/components/src/actionButton/ActionButton.tsx
> +type ActionButtonProps = { text: string } & ButtonHTMLAttributes<HTMLButtonElement>;
all those props (`className`, `disabled` ...) are coming from `ButtonHTMLAttributes`

2022-05-11 17:55 UTC, richardmccartney requested changes
Let's just add a unit test to this component to test `ref` and we should be good 👍

2022-05-11 17:55 UTC, richardmccartney commented on packages/components/src/button/Button.tsx
> +    reference,
Can we add a test just to ensure `reference` is working and is `true`

```js
  it(': set `reference` to be true on Button', () => {
    const reference = createRef<HTMLButtonElement>();
    const props = {
      reference,
    };

    expect(reference.current).toBeFalsy();

    render(<Button {...props}>Click me!</Button>);

    expect(reference.current).toBeTruthy();
  });
```

2022-05-12 09:47 UTC, dozortsev commented on packages/components/src/button/Button.tsx
> +    reference,
added the test https://github.com/transferwise/neptune-web/pull/1446/commits/b4e87a50708d306c415a86fb218b12515ad7a916

2022-05-12 10:07 UTC, richardmccartney approved these changes

2022-05-12 10:49 UTC, merged