feat: add rate component with graph icon
transferwise/neptune-web pull request #1470
Opened 2022-06-07 15:41 UTC by arikanmstf-tw

## Context
<Rate /> component using `formatRate` internally and showing rate graph icon optionally. Will be used in the context of this task: https://transferwise.atlassian.net/browse/BS-1785
Can be used at calculator as well. Using neptune colors instead of gradient colors.

## Changes
<img width="151" alt="Screenshot 2022-06-07 at 18 02 46" src="https://user-images.githubusercontent.com/57354776/172423180-5dea01d1-ce30-4af1-93fb-db6f8fe898d7.png">
<img width="109" alt="Screenshot 2022-06-07 at 18 02 52" src="https://user-images.githubusercontent.com/57354776/172423183-b1b0e2f2-0701-4e27-8658-cfd7d5e24871.png">

 

## Considerations / Results

## Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [ ] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2022-06-07 16:03 UTC, dozortsev commented on packages/components/src/rate/Rate.tsx
> +  );
please avoid using `!`

please remove `!` and just flip `return` values

2022-06-07 16:04 UTC, dozortsev commented on packages/components/src/rate/Rate.tsx
> +  options?: {
I think we don't need `config` prop, just define `significantFigures`

2022-06-07 16:13 UTC, dozortsev commented on packages/components/src/rateGraphIcon/RateGraphIcon.tsx
> +  direction: 'UP',
no need to use `prop-types` along with TypeScript

to provide default values use default value feature ([example](https://github.com/transferwise/neptune-web/blob/main/packages/components/src/actionButton/ActionButton.tsx#L14))

2022-06-08 05:29 UTC, arikanmstf-tw commented on packages/components/src/rateGraphIcon/RateGraphIcon.tsx
> +    <svg viewBox="0 0 11 8" version="1.1" xmlns="http://www.w3.org/2000/svg" id="el_m5vu-971w">
no, because this is within `tsx` file. It can't be compressed. It's not a big file tho. I tried to extract into a svg file. But it didn't support svg import

2022-06-08 05:33 UTC, arikanmstf-tw commented on packages/components/src/rate/Rate.tsx
> +  options?: {
Isn't it better this way to keep it flexible if there'd be any other configs. Because this goes to formatRate

2022-06-08 05:38 UTC, arikanmstf-tw commented on packages/components/src/rateGraphIcon/RateGraphIcon.tsx
> +  direction?: 'UP' | 'DOWN';
there is no `Position.DOWN` . And this is not about positioning tho. I think position would tell if icon would stay on the left or right side of the rate amount. But this doesn't do that

2022-06-08 13:49 UTC, dozortsev commented on packages/components/src/rate/rateGraphIcon/RateGraphIcon.less
> +  #chkcjajcfl * {
could you please give some more meaningful names to these ids

2022-06-08 13:49 UTC, dozortsev commented on packages/components/src/rate/rateGraphIcon/RateGraphIcon.less
> +  @keyframes kf_el_dre9buCDMS_an_vNQgnx9SD {
and to these keyframes

2022-06-08 13:50 UTC, dozortsev commented on packages/components/src/rateGraphIcon/RateGraphIcon.tsx
> +    <svg viewBox="0 0 11 8" version="1.1" xmlns="http://www.w3.org/2000/svg" id="el_m5vu-971w">
after optimizing it loses animation... let's leave it as it is

2022-06-08 13:52 UTC, dozortsev commented on packages/components/src/rate/rateGraphIcon/RateGraphIcon.less
> +  }
these styles are redundant

but you need add `height={16} width={16}` to `<svg ..>` element (same as we have in `@transferwise/icons`)

2022-06-08 13:54 UTC, dozortsev commented on packages/components/src/rate/rateGraphIcon/RateGraphIcon.less
> +  }
we don't need this as well

2022-06-08 13:59 UTC, dozortsev commented on packages/components/src/rate/rateGraphIcon/RateGraphIcon.tsx
> +    // eslint-disable-next-line react/jsx-filename-extension
redundant
```suggestion
    // eslint-disable-next-line react/jsx-filename-extension
```

2022-06-08 14:01 UTC, dozortsev commented on packages/components/src/rate/rateGraphIcon/RateGraphIcon.tsx
> +          <stop stopColor="#cf2929" offset="100%" />
please extract color value in variable (`colorContentNegative`)

2022-06-08 14:01 UTC, dozortsev commented on packages/components/src/rate/rateGraphIcon/RateGraphIcon.tsx
> +          <stop stopColor="#008026" offset="100%" />
same here (`colorContentPositive`)

2022-06-08 14:04 UTC, dozortsev commented on packages/components/src/rateGraphIcon/RateGraphIcon.tsx
> +  direction?: 'UP' | 'DOWN';
maybe let's call this property `trend`?

```js
<Rate trend={Position.RIGHT_TOP | Position.BOTTOM_RIGHT}
```

2022-06-08 14:06 UTC, dozortsev commented on packages/components/src/rate/Rate.tsx
> +const Rate = ({ value, direction, options }: RateProps): ReactElement => {
redundant

```suggestion
const Rate = ({ value, direction, options }: RateProps) => {
```

2022-06-08 14:12 UTC, dozortsev commented on packages/components/src/rate/Rate.story.js
> +  const direction = select('direction', ['UP', 'DOWN', null], 'UP');
by calling this prop `direction` it removed page direction global know, I would call it differently (e.g `trend`)

<img width="1527" alt="Screen Shot 2022-06-08 at 3 12 12 PM" src="https://user-images.githubusercontent.com/4015628/172638646-0b50b98e-6110-4496-885e-c899c93b84ba.png">

2022-06-08 14:18 UTC, dozortsev commented on packages/components/src/rate/rateGraphIcon/RateGraphIcon.tsx
> +    </span>
I would probably just create two icons as components in this file and keep this `span` with logic in `Rate` component so this simple logic not spread across files, I image this would same us several lines of code as well

2022-06-08 19:01 UTC, richardmccartney requested changes

2022-06-28 20:36 UTC, richardmccartney commented
Hey @arikanmstf-tw do you have any time to re-review the comments left here 😄 Let me know if you would like to run through them 👍

2022-08-22 09:03 UTC, richardmccartney commented
This PR was closed because it has been open for over 45 days with no activity.

2022-08-22 09:03 UTC, closed without merging