feat: Add optional Action Button to Definition List
transferwise/neptune-web pull request #1594
Opened 2022-09-12 13:39 UTC by NewmanJWise

## Context

We want to be able to include an action button with a definition list so that users can do things like "Copy" text.

![image](https://user-images.githubusercontent.com/79877135/189669001-3c20d5d0-206a-4ca0-be4e-a78ffabf68a5.png)

## Changes

 

- Refactored value content to have a possible action button on the right side

## Considerations / Results

Should we refactor this component to use CSS grid to make it more expandable with new columns / rows? This would mean I wouldn't have to do so many workarounds to get a button on the right hand side.

## Checklist

- [x] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [x] Changes are tested and all tests pass
- [x] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [x] Changes work in all supported browsers (don't forget IE11)
- [x] You've updated the documentation if necessary

2022-09-12 13:44 UTC, NewmanJWise commented on packages/components/src/definitionList/DefinitionList.less
> +    margin-top: -50%;
This feels nasty but if I used align items centre then the text on the left would be further down from the heading than the rest of the definitions.

2022-09-13 10:42 UTC, dozortsev commented on packages/components/src/definitionList/DefinitionList.js
> +              classNames(alignmentClassMap[layout] || '', {
please remove one `classNames(` function here

2022-09-13 10:42 UTC, dozortsev commented on packages/components/src/definitionList/DefinitionList.js
> +            <div>{value}</div>
I think we should put Action Button beneath value on small screens

<img width="667" alt="Screen Shot 2022-09-13 at 11 36 53 AM" src="https://user-images.githubusercontent.com/4015628/189880598-db28a209-6f83-4df5-8d85-b9421d71b266.png">

2022-09-13 10:42 UTC, dozortsev commented on packages/components/src/definitionList/DefinitionList.js
> +            <div>{value}</div>
just a suggestion, `useLayout` hook might be useful for you in this case

example: https://github.com/transferwise/neptune-web/blob/main/packages/components/src/drawer/Drawer.js#L17

2022-09-13 10:42 UTC, dozortsev commented on packages/components/src/definitionList/DefinitionList.js
> +        label: PropTypes.string.isRequired,
this should be `node` type, because [Action Button accepts node via `children` prop](https://github.com/transferwise/neptune-web/blob/main/packages/components/src/actionButton/ActionButton.tsx#L18)

consumer might want put icon the button

2022-09-13 16:09 UTC, helendurranttw commented on packages/components/src/definitionList/DefinitionList.js
> +        label: PropTypes.string.isRequired,
But we don't officially support icons in buttons right? It's not something we want to encourage

2022-09-13 16:20 UTC, helendurranttw commented on packages/components/src/definitionList/DefinitionList.js
> +              }),
The `alignmentClassMap[layout]` worked when it was just applying a few classes, but I think you should refactor this code to find a cleaner way of constructing all these classes based on layout and action. Maybe in its own function, even - but at least, not mixing `alignmentClassMap[layout]`, `isLayoutHorizontal(layout)` and `layout === Layout.HORIZONTAL_RIGHT_ALIGNED` on subsequent lines - it's just too difficult to reason on.

2022-09-16 15:59 UTC, NewmanJWise commented on packages/components/src/definitionList/DefinitionList.js
> +            <div>{value}</div>
I couldn't seem to replicate this, is it still happening?
<img width="533" alt="image" src="https://user-images.githubusercontent.com/79877135/190680776-78706457-e258-42db-8ebf-3709c4b0c306.png">

Do you think we should put it down the line below? On mobile it's always on the right side
![image](https://user-images.githubusercontent.com/79877135/190681120-e2770c1a-6d2e-4310-a3b2-44121ab53e6e.png)

2022-09-16 16:23 UTC, NewmanJWise commented on packages/components/src/definitionList/DefinitionList.js
> +        label: PropTypes.string.isRequired,
We could leave it as text for now and always change it & discuss later on if a request comes in?

2022-09-22 10:47 UTC, richardmccartney commented on packages/components/src/definitionList/DefinitionList.js
> +        label: PropTypes.string.isRequired,
Yes, let's leave it for now 👍

2022-09-22 10:48 UTC, richardmccartney commented on packages/components/src/definitionList/DefinitionList.js
> +            <div>{value}</div>
Happy for us to leave this as it is currently, we can pick up any design changes after 👍 @dozortsev can you let us know what browser this issue was showing on?

2022-09-26 17:24 UTC, richardmccartney requested changes

2022-09-26 17:24 UTC, richardmccartney commented on packages/docs/liveEditorCode/definitionList.code.js
> +      },
Looks like we're getting a syntax error on this page: 

```
SyntaxError: Unexpected token (28:2)
24 :       action: {
25 :         label: 'Hey',
26 :         onClick: () => console.log('Hello World!!!'),
27 :       },
28 :   ]}
       ^
```

If we can resolve this issue then we can look to merging your changes.

2022-09-26 17:25 UTC, richardmccartney commented on packages/docs/liveEditorCode/definitionList.code.js
> +      },
You can see it happening live here https://transferwise.github.io/neptune-web/branch/GPAID-1145/components/content/DefinitionList

2022-09-28 11:21 UTC, NewmanJWise commented on packages/docs/liveEditorCode/definitionList.code.js
> +      },
Fixed it, sorry about that!

2022-10-10 14:01 UTC, merged