Csprod 4455 refactor button
transferwise/neptune-web pull request #1619
Opened 2022-09-26 21:30 UTC by striccaa

## Context

**Jira ticket**: https://transferwise.atlassian.net/browse/CSPROD-4455

In the `help-center` CRAB app, we often use the Next.js-specific `<Link />` component, which has a `passHref` property, and given it's enabled, it passes the href attribute to its child element.

The current implementation of the `Button` component - which we often use wrapped in the `<Link>` component - does not support the `as` prop which would alter the rendered HTML tag, which causes two things:
1. It produces semantically incorrect HTML (see screenshot #1)
2. It breaks the styles of the button due to the button being rendered in an anchor tag (see screenshot #2)

In this PR I'm adding support to anchor tags in the `Button` component.

## Changes

 
- extended `Button` with `as` prop to support anchor tags
- added new anchor variant to `Button` story
- updated `Button` test case

## Considerations / Results

## Checklist

- [x] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [x] Changes are tested and all tests pass
- [x] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [x] Changes work in all supported browsers (don't forget IE11)
- [x] You've updated the documentation if necessary

2022-09-27 07:59 UTC, richard-better commented on packages/components/src/button/Button.tsx
> +  as?: ElementType;
Hmm, is this a breaking change? Since the new behaviour depends on the presence of a new prop, the existing behaviour is intact, right? 

If that is correct, this classifies as a minor:

> MINOR version when you add functionality in a backwards compatible manner
(from https://semver.org/ )

2022-09-27 09:46 UTC, richardmccartney requested changes

2022-09-27 09:46 UTC, richardmccartney commented on packages/components/src/button/Button.tsx
> +  as?: ElementType;
@richard-better you are correct here, the prop looks to be optional so we're not breaking the component API here at all. I'd just rebase the commit message when possible 👍

2022-09-28 09:35 UTC, tiborsaas-tw commented on packages/components/src/button/Button.story.js
> +        as={element}
It would be nice to see an example of assigning a `href` parameter as well so we could preview how it behaves as a link.

2022-09-28 09:36 UTC, tiborsaas-tw commented on packages/components/src/button/Button.tsx
> +    href?: string; // Optional due to usage of component with next/link's passHref behavior
Have you considered adding a `target` property? In some cases it might make sense to open a link in a new window.

2022-09-28 09:45 UTC, richard-better commented on packages/components/src/button/Button.tsx
> +    href?: string; // Optional due to usage of component with next/link's passHref behavior
I believe you won't need it  here explicitly in this case. If you add `as="a"`, typescript will automatically narrow the props of the component to be `AnchorProps`, and that means you can add any props supported by `a`.  The `{...props}` spread on Line 115 means it will pass those on automatically.

2022-09-28 11:22 UTC, striccaa commented on packages/components/src/button/Button.story.js
> +        as={element}
Added ✅

2022-09-28 11:23 UTC, striccaa commented on packages/components/src/button/Button.tsx
> +    href?: string; // Optional due to usage of component with next/link's passHref behavior
As @richard-better mentioned, the `AnchorHTMLAttributes<HTMLAnchorElement>` and `LinkProps` types should cover all properties that an anchor tag can have, thus, we don't need to add properties such as `target` manually.

2022-09-28 14:39 UTC, tiborsaas-tw commented on packages/components/src/button/Button.story.js
> +        as={element}
[🙇](https://emojipedia.org/person-bowing/)

2022-09-30 08:37 UTC, richardmccartney approved these changes

2022-09-30 15:23 UTC, merged