feat: add logic for display order
transferwise/neptune-web pull request #601
Opened 2020-09-28 13:52 UTC by felixxiatransferwise

## 🖼 Context

## 🚀 Changes

 
This PR adds support for `displayOrder` for object schemas.

## 🤔 Considerations

## ✅ Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [X] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2020-09-29 08:23 UTC, StevePole requested changes

2020-09-29 08:23 UTC, StevePole commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +        {props.schema.displayOrder &&
Rather than have presentational logic for both variants, let's normalise the data and have one approach to presentation e.g.
```
const orderedFields = props.schema.displayOrder || Object.keys(props.schema.properties);

orderedFields.map( ... )
```

Then you also don't need to add the WrappedGenericSchema component.

2020-09-29 08:23 UTC, StevePole commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.spec.js
> +    it('should display any properties not specified in the display order in their natural order', () => {
I'd put this in a separate 'when' as it's a different scenario.

2020-09-29 09:34 UTC, felixxiatransferwise commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +        {props.schema.displayOrder &&
There are more than 2 variants here:
- displayOrder contains all properties
- no displayOrder present
- **displayOrder contains only a subset of properties**

Therefore we probably can't do `const orderedFields = props.schema.displayOrder || Object.keys(props.schema.properties);`. If the concern is around the extra `WrappedGenericSchema` component, I could do 

```
const getOrderedFields = (schema) => {
  ...
  return orderedFields
}

const orderedFields = getOrderedFields(props.schema)

```
if this is preferable?

2020-09-29 10:00 UTC, felixxiatransferwise commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +        {props.schema.displayOrder &&
Updated.

2020-09-29 10:25 UTC, StevePole commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +          return (
Why do you need the return?

2020-09-29 10:28 UTC, StevePole commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +      const unspecifiedPropertyNames = Object.keys(schema.properties).filter(
I think we agreed that all properties should be in the order array, making this a bit redundant, but I guess it's fine to be safe.

2020-09-29 10:29 UTC, felixxiatransferwise commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +      const unspecifiedPropertyNames = Object.keys(schema.properties).filter(
Yeah adding this for safety.

2020-09-29 10:32 UTC, StevePole commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +      const unspecifiedPropertyNames = Object.keys(schema.properties).filter(
I was thinking about whether there's a cleaner way to do it e.g.
```
const ordered = [...new Set([...schema.displayOrder, ...Object.keys(schema.properties)];
```
But not 100% sure if that's order preserving.

2020-09-29 10:39 UTC, StevePole approved these changes

2020-09-29 10:40 UTC, StevePole commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +      const unspecifiedPropertyNames = Object.keys(schema.properties).filter(
It is :-) https://stackoverflow.com/questions/55460303/why-does-js-keep-insertion-order-in-set

2020-09-29 11:07 UTC, felixxiatransferwise commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +      const unspecifiedPropertyNames = Object.keys(schema.properties).filter(
Set order should be guaranteed based on insertion order in js.

2020-09-29 11:19 UTC, felixxiatransferwise commented on packages/dynamic-flows/src/jsonSchemaForm/objectSchema/ObjectSchema.js
> +      const unspecifiedPropertyNames = Object.keys(schema.properties).filter(
I was on the same post :D

2020-09-29 11:35 UTC, StevePole approved these changes
Nice

2020-09-30 09:47 UTC, helendurranttw approved these changes

2020-09-30 12:12 UTC, merged