Input accent crop
transferwise/neptune-web pull request #612
Opened 2020-10-02 14:58 UTC by andreapiras

## 🖼 Context

Input is currently cropping some character OÜ -> OU
![image](https://user-images.githubusercontent.com/16908937/94937731-e3b19080-04c7-11eb-9373-f65f3e17e7e5.png)

## 🚀 Changes

 
Changed the input from height:48px to min-height:48px and max-height:48px;

## 🤔 Considerations

## ✅ Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [ ] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2020-10-02 14:59 UTC, andreapiras commented on .circleci/config.yml
> -          type: approval
This is not working branches are not getting deployed

2020-10-07 10:53 UTC, andreapiras commented on packages/css/src/less/mixins/_forms.less
> +  min-height: @input-height;
This has been changed from 
`height: @input-height;`
to 
`min-height: @input-height;
  max-height: @input-height;`

2020-10-07 11:44 UTC, helendurranttw commented
I just tested on the deploy, doesn't look like it's fixed 😞 I think height is still being set somewhere? Also, a brief look at the code turned up another place (.select.form-control) where height is being set - make sure you also test inputs used inside the Select component.

2020-10-07 11:46 UTC, helendurranttw requested changes
- Take a look for the rogue height which is still being set on .form-control.
- Also test inside Select - I think it is an issue here too
- Could you update _forms.less to explain that this was copied directly from Bootstrap - and also add a comment explaining why we're using min-height / max-height instead of height.
- Lastly - have you tested across browsers? I didn't test that fix thoroughly

2020-10-15 13:57 UTC, andreapiras commented
> I just tested on the deploy, doesn't look like it's fixed 😞 I think height is still being set somewhere? Also, a brief look at the code turned up another place (.select.form-control) where height is being set - make sure you also test inputs used inside the Select component.
Locally on my docs it works fine 
![image](https://user-images.githubusercontent.com/16908937/96139313-a8b35200-0ef6-11eb-8577-c77bce4202cc.png)
I can't see the css on the branch docs so I think it's a cache issue

2020-10-15 15:05 UTC, andreapiras commented
> * Take a look for the rogue height which is still being set on .form-control.
> * Also test inside Select - I think it is an issue here too
![image](https://user-images.githubusercontent.com/16908937/96139513-da2c1d80-0ef6-11eb-8885-cd6a7e168327.png)

> * Could you update _forms.less to explain that this was copied directly from Bootstrap - and also add a comment explaining why we're using min-height / max-height instead of height.
Not imported anymore replaced by overrides

> * Lastly - have you tested across browsers? I didn't test that fix thoroughly
Yes IE11,FF,Chrome e Safari

2020-10-16 10:01 UTC, helendurranttw approved these changes
Rename the mixin and you're good to go

2020-10-19 10:03 UTC, merged