feat: internationalization
transferwise/neptune-web pull request #674
Opened 2020-11-13 16:10 UTC by dozortsev

## 🖼 Context

## 🚀 Changes

 

## 🤔 Considerations

## ✅ Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [ ] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2020-11-24 18:19 UTC, andreapiras commented on packages/components/lang/en.json
> +  "2xdm3a": "Close",
is this autogenerated?

2020-11-24 18:20 UTC, andreapiras commented on packages/components/package.json
> +    "babel-plugin-react-intl": "^8.2.16"
Do consumers need this?

2020-11-25 18:01 UTC, dozortsev commented on packages/components/lang/en.json
> +}
this is main source file for Crowdin, which is generated by `@formatjs/cli` out of all `*.message.js` files

see docs for more details: https://formatjs.io/docs/getting-started/message-extraction

2020-11-25 18:04 UTC, dozortsev commented on packages/components/package.json
> +    "build:default-locale-source": "formatjs extract 'src/**/*.messages.js' --out-file lang/en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]' --format lang/formatter.js",
generate main source file out of all `*.messages.js` files

2020-11-25 18:04 UTC, dozortsev commented on packages/components/package.json
> +    "build:copy-lang": "cpx 'lang/*.json' build/es/lang & cpx 'lang/*.json' build/lang",
copy translation files next to ES and UMD bundles

2020-11-25 18:07 UTC, dozortsev commented on packages/components/package.json
> +    "dev:storybook": "npx npm-watch & start-storybook -p 3001",
it's useful to watch and re generate main `en.json` file while developing against Storybook (see `"watch"` prop lower in this file)

2020-11-25 18:13 UTC, dozortsev commented on packages/components/src/avatar/Avatar.spec.js
> +import { render } from '../test-utils';
to avoid adding `<Provider >` component in every render in tests I had to "hack" render method of RTL, see `test-utils.js` file

this seem as official way todo this https://testing-library.com/docs/example-react-intl/#creating-a-custom-render-function

2020-11-25 18:15 UTC, dozortsev commented on packages/components/src/common/CloseButton/CloseButton.messages.js
> +    description: 'For `aria-label` of root button element of the component',
adding `description` is optional and it will be deleted by babel react-intl plugin while transpiling so it won't affect bundlesize

2020-11-25 18:21 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +  return <RawIntlProvider value={intl}>{children}</RawIntlProvider>;
for more into see https://formatjs.io/docs/react-intl/components#rawintlprovider

2020-11-25 18:23 UTC, dozortsev commented on packages/components/src/test-utils/index.js
> +export { render };
this seem as an official way todo this https://testing-library.com/docs/example-react-intl/#creating-a-custom-render-function

2020-11-25 18:24 UTC, dozortsev commented on packages/docs/liveEditorCode/provider.code.js
> +}
demo: https://transferwise.github.io/neptune-web/branch/i18y/components/context/Provider

2020-11-25 18:26 UTC, dozortsev commented on rfc/0004-i18n.md
> +- Status: Done
Update RFC files since some little things changed a slightly

2020-11-25 18:35 UTC, dozortsev commented on .scaffold-templates/template.4.js
> +import { render } from '../common/test';
just ignore this file 😄

2020-11-25 18:54 UTC, dozortsev commented on packages/docs/pages/about/Setup.mdx
> +    </Provider>
worth emphasize, even if none of Neptune components which you currently use in your app/library rely on translations you still should add it in you consumer app, because:

- tomorrow you might would need start use one of such components
- sometimes internal components of those that you use may rely on translations (basically to avoid any unexpected error)
- tomorrow we might add support.. let's say for theming `<Provider locale={'en'} theme={..}>` and for fast migration we want you to be already "onboard" now 🙂

2020-11-26 14:15 UTC, sbrandwoo commented on packages/components/.storybook/config.js
> +addDecorator((storyFn) => <Provider locale="en">{storyFn()}</Provider>);
It's quite useful to be able to test components with real translations. Unfortunately I think that's hard to do with the decorator at the top level - you need to specify the decorator in the stories themselves and use a knob/control to set the locale.

2020-11-26 14:21 UTC, sbrandwoo commented on packages/components/lang/de.json
> +  "0SKBlf": "Go to page {pageNumber}",
Why are you obfuscating the keys? They are very useful for translators in crowdin to understand context, and useful for developers to see where copy is being used.

2020-11-26 14:31 UTC, sbrandwoo commented on packages/components/src/provider/Provider.js
> +const cache = createIntlCache();
Do you have any documentation on this function?

Usually we can't use global caches, because they will be shared between customers - this risks leaking data between customers.

2020-11-26 14:33 UTC, sbrandwoo commented on packages/components/src/provider/Provider.js
> +    if (currentLocale !== locale) {
Regarding React hydration warnings - you won't get them because the page is rendering in English, and then re-rendering in a different language afterwards. This does mean that any text visible on the screen will flash though as it'll change in front of the user.

2020-11-26 14:36 UTC, sbrandwoo commented on packages/components/src/provider/Provider.js
> +function Provider({ locale, children }) {
I believe this `locale` is coming from the user - in which case you will need to validate it, and you'll need to map locales to the specific languages that Neptune supports. For example a locale of `es-ES` needs to load the `es.json` file.

2020-11-26 14:40 UTC, sbrandwoo commented on packages/components/lang/hk.json
> +{
`hk` isn't a valid locale. It doesn't matter than the file is called `hk.json`, but be aware that a valid value of `locale` will never be `hk`.

2020-11-26 15:10 UTC, danlaush commented on packages/components/lang/es.json
> +{
Having a single Provider wrapping the whole app seems `fine` when there's only these 4 strings, but I'm expecting that eventually there will be a bunch of form input validation messages. If I don't use a form element, that's dead code I'd rather not ship.

Did you consider giving each component its own messages Provider? I see the value in having one wrapping Provider so all the components I use can access a shared language value, but I think both can be used in tandem. The main Neptune Provider can just manage the locale, and each component can manage its own messages.

```jsx
// Render tree
<NeptuneProvider locale="es">
  <Modal>
    <InternalMessagesProvider component="modal"> // uses the NeptuneProvider context for language, but fetches messages just for the modal component
      <Message>modal.close</Message> // sorry I don't know how react-intl works
    </InternalMessagesProvider>
  </Modal>
</NeptuneProvider>
```

2020-11-26 15:11 UTC, danlaush commented on packages/components/lang/hk.json
> +{
Yeah we'll probably want this to be `zh-HK`.

2020-11-30 07:17 UTC, helendurranttw commented on packages/components/CONTRIBUTING.md
> +
```suggestion
# Internationalisation

This package has support for internationalisation, and all messages inside components should be translated if they are not required to be provided by the consumer.

Define messages using the [`defineMessages`](https://formatjs.io/docs/react-intl/api/#definemessagesdefinemessage) function in a file named `[ComponentName].message.js` next to the component file. You can then import and use them in the component.

Once you have defined the messages and agreed on copy, they must be sent to the translations vendor (Crowdin). To do this:
 
1. Run `yarn build` (it will regenerate a main source file (`en.json`) out of all `*.message.js` files)
2. Push changes (or only `en.json`) to your remote branch (this will make Crowdin notice new messages)
3. Right after that Crowdin will create a PR (where the base branch is your feature branch) with placeholders (English messages) in other translation files. It will commit into same PR (or a new PR in case you have merged the first one) with translated messages, as soon as translators translate them.

If you merge your feature PR without all the translations (which is okay-ish), Crowdin should do the same, just on the `main` branch.

```

2020-11-30 07:17 UTC, helendurranttw commented on packages/components/CONTRIBUTING.md
> +
Terrible diff.. it's just a few tweaks here and there. Nice docs!

2020-11-30 07:19 UTC, helendurranttw commented on packages/components/lang/de.json
> +  "0SKBlf": "Go to page {pageNumber}",
I agree - I guess you might be trying to save a few bytes? But as Stephen points out, they're probably worth leaving in.

2020-11-30 07:20 UTC, helendurranttw commented on packages/components/babel.config.js
> +    ],
I guess you won't need idInterpolationPattern if you remove the key hashing

2020-11-30 07:32 UTC, helendurranttw commented on packages/components/package.json
> +    "dev:storybook": "npx npm-watch & start-storybook -p 3001",
You could probably just give it its own task (`dev:translations`) - all the `dev:` tasks will get run on `dev`.

2020-11-30 07:33 UTC, helendurranttw commented on packages/components/package.json
> +    "babel-plugin-react-intl": "^8.2.16"
Is this supposed to be a peer? Seems like a dev

2020-11-30 07:42 UTC, helendurranttw commented on packages/components/src/lab/pagination/paginationLink/PaginationLink.js
> +  const ariaLabel = intl.formatMessage(
I had a peek at the deploy - it seems like the labels aren't quite right. I think we'll need more than this, too - the '...' will need its own label (maybe 'Click to access pages x - y' or something?).

<img width="1792" alt="Screenshot 2020-11-30 at 20 40 38" src="https://user-images.githubusercontent.com/61203573/100581374-85305380-334c-11eb-8a97-829997c1b974.png">

2020-11-30 07:47 UTC, helendurranttw commented on packages/components/src/provider/Provider.js
> +          setIntl(createIntlInstance(locale, en));
Under what circumstances would this fail? Maybe we should do more than just swallow the error?

Also - maybe we should revert back to `currentLocale` rather than English?

2020-11-30 07:59 UTC, helendurranttw commented on packages/docs/pages/about/Setup.mdx
> +    </Provider>
You can safely say "must" - because even if they don't need them, we will need them for our internal components :)

I think this deserves more explanation. If I haven't done this before, what locales are supported? What format do I pass them in in?

You could a further section below the code example, perhaps - with a link to the demo.

2020-11-30 07:59 UTC, helendurranttw commented on packages/docs/liveEditorCode/provider.code.js
> +}
The demo isn't working :(

I think this could use a bit of an explanation as to what it is, too - for those who haven't come across it.

2020-11-30 08:02 UTC, helendurranttw reviewed
Great work Anton - lots of moving pieces and it's coming together nicely 😄

2020-11-30 11:55 UTC, conorcussell commented on packages/components/lang/de.json
> +  "0SKBlf": "Go to page {pageNumber}",
Yep, ideally we would have some docs on key naming from the translators perspective to tell us this, but agree with Stephen, they'll at least want the key name for context

2020-11-30 12:05 UTC, conorcussell commented on packages/components/lang/es.json
> +{
I think this seems like a good idea - you could still use `IntlProvider` in the top-level Provider - but expose a function called something like `setMessages` which updates the messages passed in to that component as props. Instead of an additional Provider per component, you could maybe just use a hook

(sorry untested-code ahead)

```TypeScript
const useMessages = (componentSpecificMessages) => {
  const intl = useIntl()
  const { setMessages }  = useContext(NeptuneContext)

  useEffect(() => {
    setMessages({ ...intl.messages, ...componentSpecificMessages })
  }, [intl.locale])
}


// Button.jsx

const Button = () => {
  useMessages(componentSpecificMessages);
}
```

2020-11-30 12:07 UTC, conorcussell requested changes
The translation key names being obfuscated is the only blocker for me

2020-11-30 14:15 UTC, dozortsev commented on packages/components/package.json
> +    "dev:storybook": "npx npm-watch & start-storybook -p 3001",
👌

2020-11-30 14:18 UTC, dozortsev commented on packages/docs/liveEditorCode/provider.code.js
> +}
it works, it's just all translations files have English version by default, we haven't received translations yet

<img width="1536" alt="Screen Shot 2020-11-30 at 2 17 26 PM" src="https://user-images.githubusercontent.com/4015628/100620931-e9d0bb80-3316-11eb-82d7-a59890727bfa.png">

2020-11-30 14:20 UTC, dozortsev commented on packages/docs/pages/about/Setup.mdx
> +    </Provider>
👌

2020-11-30 14:55 UTC, danlaush approved these changes
- Agree with Conor on the string obfuscation but he's already marked this as Changes Requested
- Not a blocker for now but I'd encourage looking into only loading messages for the components I'm using

2020-11-30 15:35 UTC, dozortsev commented on packages/components/.storybook/config.js
> +addDecorator((storyFn) => <Provider locale="en">{storyFn()}</Provider>);
good point, I'm adding global know for this 

<img width="1265" alt="Screen Shot 2020-11-30 at 3 34 28 PM" src="https://user-images.githubusercontent.com/4015628/100629789-9c0d8080-3321-11eb-83bf-1f9ac15984b9.png">

2020-11-30 16:02 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +const cache = createIntlCache();
partially I configured react-intl like in this example: https://formatjs.io/docs/getting-started/installation/#minimal-application where it only says that it's optional but kinda important

there is seems really nothing particularly about this function in the docs 🤔

2020-11-30 16:10 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +const cache = createIntlCache();
Looking at [it's source code](https://github.com/formatjs/formatjs/blob/cca3ae4878aaf286c12bc7400e14e9af4e0f26ad/packages/intl/src/utils.ts#L58-L67) it seems like it only necessary for preventing of creating of some internal it's objects and don't think that it's global one.

2020-11-30 16:18 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +    if (currentLocale !== locale) {
right, is there a way to fetch data based on prop value and only then do render?

2020-11-30 16:20 UTC, dozortsev commented on packages/components/package.json
> +    "babel-plugin-react-intl": "^8.2.16"
yep, correct, it's only dev dep

2020-11-30 18:40 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +function Provider({ locale, children }) {
fixed by aligning names of files same was as country codes in Crowdin:

```
  'en',
  'ru',
  'zh-HK',
  'cs',
  'fr',
  'de',
  'hu',
  'id',
  'it',
  'ja',
  'pl',
  'pt-BR',
  'ro',
  'es-ES',
  'tr',
```

2020-11-30 18:40 UTC, dozortsev commented on packages/components/lang/hk.json
> +{
https://github.com/transferwise/neptune-web/pull/674#discussion_r532816479

2020-11-30 18:44 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +          setIntl(createIntlInstance(locale, en));
it could fail when some unknown values was passed,

good shout, I updated it to handle such cases with logs for errors https://github.com/transferwise/neptune-web/blob/i18y/packages/components/src/provider/Provider.js

2020-11-30 22:58 UTC, dozortsev commented on packages/components/src/lab/pagination/paginationLink/PaginationLink.js
> +  const ariaLabel = intl.formatMessage(
I do agree it has wrong messages aria attrs, I did review the code and seems like not quick fix, it will take quite a bit of changes to improve that which I think getting out of scope of this PR.

My changes do make thing worse so I would suggest we do that later separately. 🙂

2020-11-30 23:59 UTC, dozortsev commented on packages/docs/pages/about/Setup.mdx
> +    </Provider>
I update sentence 👍 for rest stuff I think consumers can find on providers page https://transferwise.github.io/neptune-web/branch/i18y/components/context/Provider#props

2020-12-01 09:03 UTC, oliverviljamaa commented on packages/components/lang/de.json
> +  "0SKBlf": "Go to page {pageNumber}",
The namespacing in translation keys compresses well, too!

2020-12-01 09:06 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.js
> +function Provider({ locale, children }) {
Shouldn't they align with the TransferWise values from the internal wiki instead?
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1054213243/Supported+languages

2020-12-01 09:10 UTC, oliverviljamaa commented on crowdin.yml
> +        pt-BR: pt-BR
Is it intentional that they're different from our regular, underscored (sadly) and mostly 2-letter, codes?

2020-12-01 09:11 UTC, oliverviljamaa commented on crowdin.yml
> +api_key_env: CROWDIN_KEY
Why do we need the Crowdin key? If we're using the GitHub integration, it should not be necessary.

2020-12-01 09:12 UTC, oliverviljamaa commented on crowdin.yml
> +append_commit_message: false
Do we need all of these and if yes, why? Could any of them be configured from the Crowdin GUI?

2020-12-01 09:12 UTC, oliverviljamaa commented on crowdin.yml
> +  - source: packages/components/lang/en.json
For CRAB, the standard directory naming is `i18n/${code}.json`, any reason to not follow suit here?

2020-12-01 09:13 UTC, oliverviljamaa commented on crowdin.yml
> +append_commit_message: false
That's all we have for the `BankDetails` component, for example:
https://github.com/transferwise/borderless-account-components/blob/master/crowdin.yaml

2020-12-01 09:15 UTC, oliverviljamaa commented on packages/components/CONTRIBUTING.md
> +If you merge your feature PR without all the translations (which is okay-ish), Crowdin should do the same, just on the `main` branch.
Love the docs.

2020-12-01 09:15 UTC, oliverviljamaa commented on packages/components/CONTRIBUTING.md
> +1. Run `yarn build` (it will regenerate a main source file (`en.json`) out of all `*.message.js` files)
Is there any way to avoid this? E.g., make Crowdin understand the `js` files somehow (unlikely) or utilise multiple JSON paths, like @karanjthakkar did?

2020-12-01 09:17 UTC, oliverviljamaa commented on packages/components/lang/en.json
> +}
To me, `source.json` or `messages.json` would seem cleaner for source files — especially considering all the translations are checked in here. We can still assign it under `en` in the translation map, of course.

2020-12-01 09:23 UTC, oliverviljamaa commented on packages/components/src/lab/pagination/paginationLink/PaginationLink.js
> +  const ariaLabel = intl.formatMessage(
I usually like to add contextual `TODO`s for cases like this, might be nice here?

2020-12-01 09:25 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.js
> +  const [intl, setIntl] = useState(createIntlInstance(defaultLocale, en));
Why can't we create it with the `locale` from the prop?

2020-12-01 09:30 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.spec.js
> +  it('tests that provider does not add any elements in the DOM', () => {
_Provider tests..._ sounds a bit weird, why not _Provider does not add..._?

2020-12-01 09:30 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.spec.js
> +      <Provider {...{ locale }}>
Can't we?
```suggestion
      <Provider locale={locale}>
```

2020-12-01 09:31 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.spec.js
> +  test.each([
Should we test a missing locale, too?

2020-12-01 09:33 UTC, oliverviljamaa commented on packages/components/src/test-utils/index.js
> +export { render };
Nice, perhaps I'd even link this in a comment in the code.

2020-12-01 09:34 UTC, oliverviljamaa commented on packages/docs/liveEditorCode/provider.code.js
> +}
Neat!

2020-12-01 09:37 UTC, oliverviljamaa reviewed
Amazing work, @dozortsev 🚀 🌐 💪 I left some feedback, happy to discuss!

2020-12-01 09:40 UTC, danlaush commented on packages/components/src/provider/Provider.js
> +function Provider({ locale, children }) {
I'm on board with migrating to IETF `zh-HK` over `zh_HK`, but yeah everywhere else just uses `pt` and `es`.

2020-12-01 09:46 UTC, danlaush commented on crowdin.yml
> +append_commit_message: false
Maybe you have a tip for this @oliverviljamaa but I've noticed that if you don't specify the two-letter code, crowdin downloads the file as a 5-char string. Here's public-nav's dist folder, you can see the languages that don't have a 2-letter mapping 

![image](https://user-images.githubusercontent.com/1204500/100723430-a7ac8600-33b9-11eb-904d-21c5c432feed.png)
That's even when crowdin's UI shows it as a 2-char string, e.g. https://crowdin.com/project/public-navigation/bg
![Screenshot 2020-12-01 at 09 44 16](https://user-images.githubusercontent.com/1204500/100723775-1984cf80-33ba-11eb-9c54-2360d21659fd.png)

2020-12-01 10:22 UTC, sbrandwoo commented on packages/components/src/provider/Provider.js
> +function Provider({ locale, children }) {
The param is `locale` and this is a public package, so any values here should be IETF.

2020-12-01 10:30 UTC, sbrandwoo commented
I think I'd prefer this PR to go live without the dynamic loading of language files - I'm not convinced it's the right solution.

I'd prefer if we could load translation files on the server-side somehow, and pass these translations into the page, rather than relying on the page loading the translations for themselves later.

This would overall be better for performance in terms of download time, and would prevent the page from being rendered twice, with a lag between the two renders.

2020-12-01 10:36 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.js
> +function Provider({ locale, children }) {
Happy with either, as long as it doesn't add extra mapping burden to all consumers.

2020-12-01 11:09 UTC, twrdjpalmer commented
Have to agree with @sbrandwoo here. Lazily loading the correct language seems far less than ideal. I've been thinking about this problem recently, after discussions with @danlaush about how Crab Lienzo is going to handle it.

Rather than put all the load on neptune itself, we could provide the tools for the consumer to enable server-side translations.

This could be a middleware, which reads the translations from `node_modules` and includes them in crab's `res.locals` for the consumer to provide to the `NeptuneProvider` component. Much in the same way the current translation's middleware works.

This is quite common amongst other libs, such as `emotion` which requires you to call something in `getInitialProps` to avoid memory leaks.

Of course, this won't work for all consumers. They can use said middleware as a foundation to roll their own solution, which could be contributed back to neptune as necessary.

2020-12-01 11:14 UTC, danlaush commented
I definitely pushed Anton toward this solution, which I'm sure was influenced by the fact that I came up with it working on a client-side-only app [rate-alerts](https://transferwise.com/tools/exchange-rate-alerts/). For that use case it makes for a really smooth language change but I wonder if I would have come at the problem differently if I'd worked on a Crab app first.

2020-12-01 22:22 UTC, andreapiras commented on packages/components/lang/formatter.js
> +  Object.entries(messages).forEach(([id, msg]) => {
This is [not supported on IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries). So it will probably results in polyfills to be added to the final bundle, better to use Object.keys

2020-12-01 22:29 UTC, andreapiras commented on packages/components/src/chevron/Chevron.spec.js
> +import { render } from '../test-utils';
Do we need to add it even in files where we don't use translations?

2020-12-01 22:32 UTC, andreapiras commented on packages/components/src/lab/pagination/paginationLink/PaginationLink.js
> +    active ? messages.ariaLabelActive : messages.ariaLabelPassive,
maybe you meant `ariaLabelInactive` ? 😅

2020-12-01 22:35 UTC, andreapiras commented on packages/components/src/provider/Provider.js
> +function Provider({ locale, children }) {
I think i would give it a more recognizable name `NeptuneProvider`

2020-12-01 22:42 UTC, andreapiras commented on packages/components/src/provider/Provider.js
> +      if (supportedLocale.includes(locale)) {
includes is not supported on Ie11

2020-12-02 08:13 UTC, helendurranttw commented on packages/components/src/provider/Provider.js
> +      if (supportedLocale.includes(locale)) {
We have a polyfill though :)

2020-12-02 11:15 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +      if (supportedLocale.includes(locale)) {
yep, babel provides polyfills for JS native API

2020-12-02 11:29 UTC, andreapiras commented on packages/components/src/provider/Provider.js
> +      if (supportedLocale.includes(locale)) {
Yes I know, but that means polyfills will get added when really we can avoid by using indexOf

2020-12-02 15:11 UTC, dozortsev commented on packages/components/src/chevron/Chevron.spec.js
> +import { render } from '../test-utils';
I would say yes, https://github.com/transferwise/neptune-web/pull/674#discussion_r530583387

2020-12-03 08:34 UTC, oliverviljamaa commented on crowdin.yml
> +append_commit_message: false
Public navigation has `%locale%`, not `%two_letter_code%` — if you have the latter, it'll have 2-letter code for all the locales, and the only mapping we'll have to do is `zh` to `zh_HK`.

2020-12-03 12:51 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +function Provider({ locale, children }) {
I know, Provider is not quite regular component e.g like Button one but for me NeptuneProvider feels same like we would name Button component a NeptuneButton, I pick generic name and didn’t name it e.g TranslationProvider because in future we might extend it’s functionality to provide context for other stuff.

2020-12-09 14:19 UTC, dozortsev commented on packages/components/lang/en.json
> +}
I see but as was suggested https://github.com/transferwise/neptune-web/pull/674#issuecomment-736385958 with new interface consumers will need load file for by themselves, and I think it would be convenient if they would be able todo that just via locale value without any extra mapping (locale to file name) when they would do dynamic import

```js
const file = import(`@transferwise/components/build/lang/${locale}.json`)
```

2020-12-09 14:21 UTC, dozortsev commented on packages/components/src/test-utils/index.js
> +export { render };
👌

2020-12-09 18:39 UTC, dozortsev commented on packages/components/src/provider/Provider.spec.js
> +  test.each([
test will fail because of warning of unrecognized value passed into prop ([test setup](https://github.com/transferwise/neptune-web/blob/a9da4cd0bba2535bc7bb8222ddb1cde9a27e6cba/packages/test-config/config/setupTests.js#L12-L13)).

2020-12-09 18:40 UTC, dozortsev commented on packages/components/src/provider/Provider.spec.js
> +  it('tests that provider does not add any elements in the DOM', () => {
fixed

2020-12-09 18:46 UTC, dozortsev commented on crowdin.yml
> +  - source: packages/components/lang/en.json
renamed to `i18n`

2020-12-09 18:51 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +      locale: locale.replace('_', '-'),
`createIntl` does support code with underscore

2020-12-10 10:50 UTC, conorcussell commented on packages/components/i18n/en.json
> +  "np.CloseButton.aria-label": "Close",
obviously this is about as minor as it gets, but, whats with the mix of kebab and camel case in these key names?

2020-12-10 10:51 UTC, conorcussell approved these changes

2020-12-10 11:10 UTC, twrdjpalmer commented on packages/docs/pages/_app.js
> +  }
Can you provide documentation for the recommended way of setting up the use of neptune's translations in the consumer?

2020-12-10 14:08 UTC, dozortsev commented on packages/components/i18n/en.json
> +  "np.CloseButton.aria-label": "Close",
👌

2020-12-10 14:25 UTC, dozortsev commented on packages/docs/pages/_app.js
> +  }
good point, updated notes in [Setup.mdx](https://github.com/transferwise/neptune-web/pull/674/files#diff-64a81e19012827758c14ce4ed4f10be52fa187b4471a7c4955a599caa57055abR51-R65) ([rendered](https://transferwise.github.io/neptune-web/branch/i18y/about/Setup))

2020-12-10 22:11 UTC, helendurranttw commented on packages/components/src/common/CloseButton/CloseButton.messages.js
> +  ariaLabel: {
Why do the generated translation files have `np.CloseButton.aria-label` instead of `np.CloseButton.ariaLabel`?

2020-12-10 22:23 UTC, helendurranttw commented on packages/docs/pages/components/context/Provider.mdx
> +<GeneratePropsTable componentName="Provider" />
```suggestion

export const defaultLocale = 'en';

`Provider` provides contextual data such as translations to components. See the [usage guide](https://transferwise.github.io/neptune-web/branch/i18y/about/Setup#usage) for more.

<LiveEditorBlock code={code} scope={{ Provider, Select, FormattedMessage, messages, supportedLanguages, defaultLocale }} />
<GeneratePropsTable componentName="Provider" />
```

2020-12-10 22:25 UTC, helendurranttw commented
This looks great Anton. I did notice the example you have on the docs at the moment isn't working - potentially related to the comment I made about `np.CloseButton.aria-label` vs `np.CloseButton.ariaLabel`? Also the tests are failing at the moment (maybe also related?).

Once you've fixed the docs example and the tests and addressed the comments - I think it's good to go.

2020-12-11 09:29 UTC, twrdjpalmer commented on packages/components/src/provider/Provider.js
> +  'en',
Good chance we also pass `en_US`—do we need to support that here too?

2020-12-11 13:16 UTC, oliverviljamaa commented on crowdin.yml
> +        id: id
Why would this not work? One less thing to change when supporting a new language.
```suggestion
      two_letters_code:
        zh-HK: zh_HK
```

2020-12-11 13:17 UTC, oliverviljamaa commented on packages/components/i18n/en.json
> +  "np.CloseButton.ariaLabel": "Close",
Why do we need the namespacing? If we do, why not write _neptune_ in full?

2020-12-11 13:20 UTC, oliverviljamaa commented on packages/components/i18n/formatter.js
> +  return results;
Is this the same as:
```suggestion
  return Object.fromEntries(
    Object.entries(messages).map(([id, { defaultMessage }]) => ([id, defaultMessage])),
  );
```

2020-12-11 13:22 UTC, oliverviljamaa commented on packages/components/i18n/zh_HK.json
> +}
Is this all the copy we want to add for now or will there be separate PRs for more? (general Q, not related to this this language)

2020-12-11 13:26 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.js
> +  'en',
Do I understand correctly that although we don't support `en_US` as a separate language in our systems (Crowdin, etc.), but want to keep showing it as a language customers can select? If yes, could we keep the knowledge of `en_US` higher up and make the conversion in CRAB, etc.?

2020-12-11 13:26 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.js
> +const Locales = [
`LOCALES` for constant naming? `PascalCase` is usually for enums, components, types, and classes.

2020-12-11 13:38 UTC, oliverviljamaa commented on packages/docs/pages/about/Setup.mdx
> +import en from '@transferwise/components/build/i18n/de.json';
Nice!

2020-12-11 13:39 UTC, oliverviljamaa commented on packages/docs/pages/about/Setup.mdx
> +**Note:** `Provider` must be used in repositories which bundle components (i.e. lists `@transferwise/components` as a `dependency`). For repositories which don't bundle components (typically those th
👏

2020-12-11 14:37 UTC, twrdjpalmer commented on packages/components/src/provider/Provider.js
> +  'en',
We use `en_US` bit in the money transfer homepage, so want to keep that value around. For as long as the code is in our [supported language matrix](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1054213243/Supported+languages), we should support it here too, right? I'm not sure, just making sure we've thought about it :)

2020-12-11 14:43 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.js
> +  'en',
I'm not sure either — at some point, translators recommended us to stop differentiating between `en` and `en_US` (hence the _use source directly_ on the languages page), but it's still present in language selectors.

2020-12-14 09:29 UTC, sbrandwoo commented on packages/components/src/provider/Provider.js
> +  'zh_HK',
`zh_HK`, with an underscore, is not a valid "locale" and should never be mentioned in a variable called `locale`.

2020-12-14 09:33 UTC, sbrandwoo commented on packages/components/src/provider/Provider.js
> +  'en',
> but want to keep showing it as a language customers can select?

This is my understanding too. In still affects how dates are formatted. It's also a good example of where TW language doesn't match locale, as our language of `en` is British English, whereas the international convention is to have `en` as US English.

Crab will use the following:
- Language US English `en_US`, locale `en`
- Language British English `en`, locale `en-GB`

2020-12-14 09:40 UTC, sbrandwoo commented on packages/components/src/provider/Provider.js
> +  'zh_HK',
For reference, locales should be [BCP 47 / IETF language tags](https://en.wikipedia.org/wiki/IETF_language_tag).

An easy way to test is to see if it works with the browser's Intl library:

```
new Date().toLocaleDateString("zh_HK")
```

2020-12-14 09:42 UTC, sbrandwoo commented
As this is a public package I believe we should be as correct as possible when it comes to locales. Values such as `en_US` and `zh_HK`, with underscores, exist because of TW tech debt (Webapp won't accept hyphens) and we should avoid them where possible.

2020-12-14 09:45 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.js
> +  'zh_HK',
I agree with @sbrandwoo — even if this wasn't a public package, I'd aim to hide our legacy-related constraints as much as possible, rather than spread it further.

Perhaps we could accept standard locales and map to the best option?

2020-12-14 15:28 UTC, dozortsev commented on packages/components/src/common/CloseButton/CloseButton.messages.js
> +  ariaLabel: {
this is now fixed, 

as a developer you don't have to deal with translation json files, you only make changes in `*.messages.js` and update Crowdin source file (`en.json`) by running `yarn build` then push and wait until Crowdin update other files for you https://github.com/transferwise/neptune-web/pull/728

2020-12-14 15:35 UTC, dozortsev commented on packages/components/i18n/en.json
> +  "np.CloseButton.ariaLabel": "Close",
okey, fixed

2020-12-14 15:40 UTC, dozortsev commented on packages/components/i18n/zh_HK.json
> +}
yeah, we there will be follow up PR

don't want do that in this PR as it's already pretty big

2020-12-14 15:41 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +const Locales = [
👌

2020-12-14 17:50 UTC, dozortsev commented
Made a change to support only IETF language tag, I agree we should only them and don't tight our Neptune library to TW specifics.

https://transferwise.github.io/neptune-web/branch/i18y/components/context/Provider here in Select you can see list of supported locale codes, if unrecognized code supplied the component will fallback to `en`.

cc @oliverviljamaa @sbrandwoo @twrdjpalmer

2020-12-15 12:21 UTC, oliverviljamaa commented on packages/components/src/provider/Provider.js
> +  if (LOCALES.includes(locale)) {
Could we even be more flexible and support _language + region_ locales, especially considering we support `zh_HK`? We could just check if we have `locale.slice(0,2)` and fall back to that if we do.

2020-12-15 12:23 UTC, oliverviljamaa approved these changes
Awesome job on this 🚀

2020-12-15 14:10 UTC, sbrandwoo commented on packages/components/src/provider/Provider.js
> +  if (LOCALES.includes(locale)) {
Crab will give `en-GB` and `en-US` locales, so just checking the first two characters sounds good as a fallback.

@danlaush might have further thoughts about how this will work with lienzo languages.

2020-12-15 14:14 UTC, sbrandwoo commented on packages/docs/pages/about/Setup.mdx
> +import(`@transferwise/components/build/i18n/${locale}.json`);
As mentioned in `Provider`, we might need to match IETF locales into locales that Neptune supports. That would also be useful here when selecting which translation to load.

Perhaps Neptune could expose a function such as `toNeptuneLocale(locale: string): string` that consumers can use to map IETF locales to supported Neptune locales?

2020-12-15 14:42 UTC, danlaush commented on packages/components/src/provider/Provider.js
> +  if (LOCALES.includes(locale)) {
Thanks for thinking of Lienzo <3 We'll normalise the language from Lienzo before we use it anywhere—it's a free text field so there are >70 uniques in use. https://looker.tw.ee/sql/cn2v3hfgpthxwc

I think this could be fine for now, with one thing to think about. When (not if—only a matter of time) we start supporting mainland Chinese (`zh`, `zh-Hans`, `zh-CN`), how could we handle that separately from `zh-HK`?

2020-12-15 14:47 UTC, dozortsev commented on packages/components/src/provider/Provider.js
> +  if (LOCALES.includes(locale)) {
@danlaush we will add support for them `zh`, `zh-Hans`, `zh-CN` (meaning add it in [list of supported locales](https://github.com/transferwise/neptune-web/pull/674/files#diff-2e5996335d2ef854008793db05763e311536f765f40dd7a340f5c8ed2eb86914R47) and provide you a JSON file of it)

2020-12-15 15:04 UTC, danlaush commented on packages/components/src/provider/Provider.js
> +  if (LOCALES.includes(locale)) {
I think in that case we couldn't safely use the two-letter code as a fallback. If `zh` existed and someone passed in `zh_HK`, it would clip it to `zh` and use simplified Chinese, which wouldn't be readable by traditional Chinese readers. Do I understand it right?

2020-12-15 15:38 UTC, sbrandwoo approved these changes

2020-12-15 15:50 UTC, dozortsev commented on packages/docs/pages/about/Setup.mdx
> +import(`@transferwise/components/build/i18n/${locale}.json`);
add mapping API https://github.com/transferwise/neptune-web/pull/674/commits/1e2d6222f2304f6a4188e70b7c7732b8aa66eafc and updated docs https://github.com/transferwise/neptune-web/pull/674/commits/f6747be1bb5efa90fd2f3e8f24d4e367ce819ffb

2020-12-15 15:51 UTC, twrdjpalmer commented on packages/components/src/provider/Provider.js
> +    console.warn(`Unsupported locale value was provided: '${locale}', use English by default`);
```suggestion
    console.warn(`Unsupported locale value was provided: '${locale}', defaulting to 'en'`);
```

2020-12-15 15:53 UTC, twrdjpalmer commented on packages/docs/pages/about/Setup.mdx
> +import en from '@transferwise/components/build/i18n/de.json';
```suggestion
import de from '@transferwise/components/build/i18n/de.json';
```

2020-12-15 15:54 UTC, twrdjpalmer commented on packages/docs/pages/about/Setup.mdx
> +    <Provider i18n={{ locale: currentLocale, messages: translations[currentLocale] }}>
Might be OTT, but might be worth adding a note that this is the spec locale & not the TW internal one, so we remember to do the conversion

2020-12-15 15:54 UTC, twrdjpalmer approved these changes

2020-12-16 04:29 UTC, helendurranttw commented on packages/components/src/test-utils/index.js
> +  return rtlRender(ui, { wrapper: Wrapper, ...renderOptions });
Abbreviating React Testing Library is going to get confusing once we start talking more about Right To Left 😀

2020-12-16 04:30 UTC, helendurranttw approved these changes
👏.  🎉.  💪

2020-12-16 11:20 UTC, andreapiras approved these changes

2020-12-16 13:48 UTC, merged

2020-12-16 17:15 UTC, dozortsev commented on packages/components/src/test-utils/index.js
> +  return rtlRender(ui, { wrapper: Wrapper, ...renderOptions });
fixed