fix: Bump @transferwise/icons in @transferwise/components
transferwise/neptune-web pull request #687
Opened 2020-11-20 10:34 UTC by conorcussell

## 🖼 Context

@transferwise/components bundles its own icons, which means that if your app has a different version installed
you will get an error due to attribute mismatch when using with SSR.

## 🚀 Changes

- [x] Bumps `@transferwise/icons` to the latest version in `@transferwise/components`

## 🤔 Considerations

This bumps icons to the latest version, but if we expect consumers to also be using @transferwise/icons in their apps
we could consider moving it into peerDependencies.

## ✅ Checklist

- [x] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [x] Changes are tested and all tests pass
- [x] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [x] Changes work in all supported browsers (don't forget IE11)
- [x] You've updated the documentation if necessary

2020-11-20 10:47 UTC, helendurranttw approved these changes

2020-11-20 11:16 UTC, helendurranttw requested changes
Hey Conor, I think the test snapshots need updating :)

2020-11-20 11:28 UTC, conorcussell commented
@helendurranttw done in https://github.com/transferwise/neptune-web/pull/687/commits/99a45caf0cd9aa1e7403a7a6daef10dee38d3dac thanks!

2020-11-26 16:52 UTC, conorcussell commented
closing this as the dependency was moved to peerDeps

2020-11-26 16:52 UTC, closed without merging