fix: select inside modal
transferwise/neptune-web pull request #709
Opened 2020-12-01 16:30 UTC by dozortsev

## 🖼 Context

## 🚀 Changes

 

## 🤔 Considerations

## ✅ Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [ ] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2020-12-01 21:20 UTC, andreapiras requested changes
We need to implement the select dropdown reposition

2020-12-03 15:50 UTC, andreapiras commented on packages/components/src/modal/Modal.js
> +  static Container = {
I think having a prop called 'fitHeight' = {true|false} would be enough

2020-12-03 15:50 UTC, andreapiras commented on packages/components/src/modal/Modal.js
> +              { 'tw-modal--adaptive': container === Container.ADAPTIVE },
This would become
'tw-modal-fit-height' : fitHeight

2020-12-03 15:55 UTC, dozortsev commented on packages/components/src/modal/Modal.js
> +  static Container = {
I prefer we use enum approach here (please check [bool vs enum](https://material-ui.com/guides/api/#boolean-vs-enum)) as it's more scalable approach, we might add third type of container in Modal, and/or we might add a few more types of containers [there](https://github.com/transferwise/neptune-web/pull/709/files#diff-9b93bb4e4e56b73b6c4bfc3a638d6ea371472568c45d7a66cdb1dd63e7c1bd3aR1) for other components which won't be used by Modal, so it's not only for Modal, tomorrow it could be about Popover, Alert etc.

2020-12-03 15:58 UTC, dozortsev commented on packages/components/src/modal/Modal.js
> +  static Container = {
I'm fine to consider to change API naming, 

wdyt?
```ts
container: 'fitContent' | 'fitMaxHeight'
```

2020-12-03 15:59 UTC, dozortsev commented on packages/components/src/modal/Modal.js
> +              { 'tw-modal--adaptive': container === Container.ADAPTIVE },
https://github.com/transferwise/neptune-web/pull/709#discussion_r535359292

2020-12-03 21:17 UTC, helendurranttw commented on packages/components/src/modal/Modal.js
> +  static Container = {
I think container is a little bit too generic - how about `contentFit`? I like the idea of a single boolean prop, but am also ok with the enum - if you rename it to be a little more descriptive. How about: `contentFit: 'scroll' | 'expand'`? Or for a boolean: `contentScroll: true | false`?

Also - one quick note on the enum - let's not put it in common just yet - leave it inside Modal, and we can pull it out when we want to reuse it. I can't see this being a frequently used prop.

2020-12-03 21:17 UTC, helendurranttw reviewed
Looks great Anton, thank you.

2020-12-03 21:24 UTC, helendurranttw commented
@dozortsev - looks like there's an issue in IE11 - the modal isn't rendering correctly.

2020-12-07 11:33 UTC, dozortsev commented on packages/components/src/modal/Modal.js
> +  static Container = {
@helendurranttw thanks for feedback

re. `contentFit: 'scroll' | 'expand'` I would not use word "expand" because it **adapting** to content size which mean that sometimes it shrinks.

<details>
<summary>Example of adaptive modal container (shrinked, expanded and then again shrinked):</summary>
<img width="985" alt="Screen Shot 2020-12-07 at 11 22 40 AM" src="https://user-images.githubusercontent.com/4015628/101345299-bfcf4a00-387e-11eb-9f96-b878faec1e43.png">
<img width="818" alt="Screen Shot 2020-12-07 at 11 22 25 AM" src="https://user-images.githubusercontent.com/4015628/101345305-c1007700-387e-11eb-933e-ec1969d89cdb.png">
<img width="746" alt="Screen Shot 2020-12-07 at 11 22 16 AM" src="https://user-images.githubusercontent.com/4015628/101345307-c1990d80-387e-11eb-8faf-def7fccd7c97.png">
</details>

I think "adaptive" is perfect word here 🙂

---

re. following:

> ...Also - one quick note on the enum - let's not put it in common just yet - leave it inside Modal, and we can pull it out when we want to reuse it. I can't see this being a frequently used prop.

I'm afraid that we might forget about it, and it won't be discoverable for contributors either if we only store in inside this component. I see no harm to define it in common, this way it will find it's second usage faster, defining something in common tell contributors that this meant to be reused so we will avoid people inventing 🙂

2020-12-07 13:05 UTC, oliverviljamaa commented
Having the options behind the footer feels like a bug to me. Did you consider showing them above the footer and above the modal for modals with the current, `scrollable`, container, too?
![image](https://user-images.githubusercontent.com/5443561/101354257-cd60f000-38cf-11eb-9f45-8e092b5de64f.png)

2020-12-07 13:13 UTC, oliverviljamaa commented on packages/components/src/modal/Modal.js
> +  static Container = {
> we might add third type of container in Modal
What could that be? Just challenging and wondering whether we're sacrificing a bit of readability for the unknown.

Regarding naming — I feel the option defines how the _height_ of the modal is determined, either by _content_ or _screen/viewport (height)_, so would recommend using something along those lines in the lingo.

2020-12-07 13:16 UTC, oliverviljamaa commented on packages/components/src/modal/Modal.js
> +  static Container = {
`height*: 'content' | 'viewport'`, where `*` is a word I don't have yet. `heightBy`? `heightDeterminedBy`? 🤔

2020-12-07 13:37 UTC, andreapiras commented
> Having the options behind the footer feels like a bug to me. Did you consider showing them above the footer and above the modal for modals with the current, `scrollable`, container, too?
> <img alt="" width="480" src="https://user-images.githubusercontent.com/5443561/101354257-cd60f000-38cf-11eb-9f45-8e092b5de64f.png">

Hey @oliverviljamaa, at the moment the body of modal has an overflow-y:auto, so the dropdown can't exceed tw-modal-body boundaries. The only solution we could see here is too render the select modal into a portal which would then cause many headaches  on attaching to the triggering field (also imagine scrolling etc). So for now if you want to use select in modal you have to use adaptive modals that will adapt to the content. If you have any other idea please share with us :)

2020-12-07 13:46 UTC, dozortsev commented on packages/components/src/modal/Modal.js
> +  static Container = {
@oliverviljamaa 

> ..What could that be? Just challenging and wondering whether we're sacrificing a bit of readability for the unknown.

I don't know, but it can be third type of container for Modal or for another component

2020-12-07 16:18 UTC, andreapiras commented on packages/docs/liveEditorCode/modal.code.js
> +        container={Modal.Container.ADAPTIVE}
should we document position too here?

2020-12-07 16:21 UTC, andreapiras commented on packages/components/src/modal/Modal.js
> +  static Container = {
I think container is way too generic and my preference would definitely go for boolean as I don't see any other use cases. If we use tight the prop name with the height (fitHeight true or false) if tomorrow we'll need another prop we'll be able to introduce it in the same way -> fitWidth={true|false} etc

2020-12-08 11:19 UTC, helendurranttw commented on packages/components/src/modal/Modal.js
> +  static Container = {
scroll: content | viewport

2020-12-08 12:56 UTC, dozortsev commented on packages/docs/liveEditorCode/modal.code.js
> +        container={Modal.Container.ADAPTIVE}
added

2020-12-08 14:02 UTC, andreapiras commented on packages/components/src/dimmer/Dimmer.spec.js
> +    expect(component.find('.dimmer').hasClass('dimmer--scrollable')).toBe(true);
```suggestion
  it('is not scrollable when scrollable=false', () => {
    expect(component.find('.dimmer--scrollable')).toHaveLength(0);
  });

  it('is scrollable when scrollable=true', () => {
    component.setProps({ scrollable: true });
    expect(component.find('.dimmer--scrollable')).toHaveLength(1);
```

2020-12-08 14:05 UTC, andreapiras approved these changes

2020-12-09 12:34 UTC, oliverviljamaa commented
> Hey @oliverviljamaa, at the moment the body of modal has an overflow-y:auto, so the dropdown can't exceed tw-modal-body boundaries. The only solution we could see here is too render the select modal into a portal which would then cause many headaches on attaching to the triggering field (also imagine scrolling etc). So for now if you want to use select in modal you have to use adaptive modals that will adapt to the content. If you have any other idea please share with us :)

Thanks, @andreapiras! The workarounds don't seem great indeed. I'm wondering why we need the `overflow-y:auto`?

2020-12-09 13:01 UTC, merged