feat: Accordion changes
transferwise/neptune-web pull request #848
Opened 2021-03-12 10:59 UTC by OFFLlNE

## 🖼 Context

In HAT Team we are working to create a Modal that contains Accordion.

## 🚀 Changes

 
 - Add icon capabilities to Accordion
 - Add open&close animation
 - Open & Close only on user behavior (only close when user clicks to close)
 - fix: Title overflow
 - Accordion Item content overflow and fitting adjustments
 - Accordion to functional component
 - 

## 🤔 Considerations

## ✅ Checklist

- [x] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [x] Changes are tested and all tests pass
- [x] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [x] Changes work in all supported browsers (don't forget IE11)
- [x] You've updated the documentation if necessary

2021-03-12 12:27 UTC, dozortsev commented on packages/components/src/accordion/AccordionItem/AccordionItem.js
> +  isInitiallyOpen: Types.bool.isRequired,
plus we don't add prefix `is` for boolean props, so I would call this prop `open` same way as we do in a couple other components.

2021-03-12 12:44 UTC, dozortsev commented on packages/components/src/accordion/Accordion.js
> +const Accordion = ({ items, onClick, indexOpen }) => {
thanks for refactoring to functional component ❤️

2021-03-12 12:50 UTC, dozortsev commented on packages/components/src/accordion/AccordionItem/AccordionItem.js
> +  icon: Types.node,
@andreapiras you might would need illustration there in your project

<img width="320" alt="Screen Shot 2021-03-04 at 11 18 57 AM" src="https://user-images.githubusercontent.com/4015628/110942263-7dac1d80-8331-11eb-9fd0-619f11580312.png">

so I think we should call this prop differently, `media`?

2021-03-12 13:15 UTC, helendurranttw commented on packages/components/src/accordion/AccordionItem/AccordionItem.js
> +  icon: Types.node,
Orrrr we can convince them to use icons. @gusso ?

2021-03-15 09:28 UTC, OFFLlNE commented
Also curious how do the docs update work exactly?
Do I just go to https://transferwise.github.io/neptune-web/components/content/Accordion and click the edit these docs on Github button and add the changes? As I did not see any .mdx files in file tree

2021-03-15 10:27 UTC, dozortsev commented
@OFFLlNE all docs (.mdx) files should be in docs package (`neptune-web/packages/docs/pages/components/content/Accordion.mdx`)

2021-03-15 11:32 UTC, OFFLlNE commented
> @OFFLlNE all docs (.mdx) files should be in docs package (`neptune-web/packages/docs/pages/components/content/Accordion.mdx`)

Based on that
>The documentation and the new npm release will be automatically deployed when merging changes to main

I do not need to do anything else, but just wait for all the reviews 👼

2021-03-15 13:35 UTC, andreapiras commented on packages/components/src/accordion/Accordion.less
> +  .accordion-content {
@OFFLlNE Has this animation been discussed with a designer?

2021-03-15 13:38 UTC, OFFLlNE commented on packages/components/src/accordion/Accordion.less
> +  .accordion-content {
Yes, Gusso approved animation. Is there a way Gusso can test this animation himself as well on a github pages or story somehow? We have not showed the end result - but tried to mimic what we have on our legacy bootstrap accordion

2021-03-15 13:48 UTC, andreapiras commented on packages/components/src/accordion/Accordion.js
> -class Accordion extends PureComponent {
Hey this would be great to change but unfortunately it is a big breaking change. If you can migrate to a functional component without introducing any change in the behavior it would be great.

2021-03-15 13:57 UTC, OFFLlNE commented on packages/components/src/accordion/Accordion.js
> -class Accordion extends PureComponent {
Why is it a breaking change? We are not changing any required props?

2021-03-15 14:00 UTC, andreapiras commented on packages/components/src/accordion/Accordion.js
> -class Accordion extends PureComponent {
In this case we moved from uncontrolled component (statefull) to a controlled component (stateless), Accordion now relies on parent to pass indexOpen while before it use internal state to manage the open AccordionItem. I would recommend to introduce just the minimal changes and work on this for the next breaking change release

2021-03-15 14:01 UTC, andreapiras requested changes
We don't want to introduce breaking changes just right now because v35 has just been released

2021-03-15 14:04 UTC, andreapiras commented on packages/components/src/accordion/Accordion.less
> +  .accordion-content {
You can demo via this link that you can find at the bottom of your PR https://transferwise.github.io/neptune-web/branch/accordion-hat/index.html

2021-03-15 14:06 UTC, OFFLlNE commented on packages/components/src/accordion/Accordion.js
> -class Accordion extends PureComponent {
I am not sure I follow. We are not relying on it because it is still an optional prop. If you are not passing anything tho whole thing is just closed. And when you do pass it will use that inside AccordionItem.

Maybe I am missing something, but cannot see how anything has changed for anybody who consumes it.

2021-03-16 08:38 UTC, gusso commented
The cursor is set to `pointer` over the convent area, it should be `auto` so the user knows they can interact with the content, such as selecting text.

2021-03-17 12:45 UTC, andreapiras submitted a review, later dismissed

2021-03-17 16:02 UTC, andreapiras approved these changes

2021-03-17 16:11 UTC, helendurranttw commented on packages/components/src/accordion/AccordionItem/AccordionItem.js
> +  icon: Types.node,
We've decided not to support this for the moment.

2021-03-18 13:43 UTC, andreapiras commented on packages/components/src/accordion/Accordion.story.js
> +  // const value = object('items', items);
```suggestion
```

2021-03-18 13:43 UTC, andreapiras commented on packages/components/src/accordion/Accordion.story.js
> +  // const value = object('items', items);
```suggestion
```

2021-03-18 14:10 UTC, merged