feat: add forwardRef, fix MoneyInput accepting invalid input,
transferwise/neptune-web pull request #914
Opened 2021-04-26 14:26 UTC by arikanmstf-tw

Quote from the old [PR](https://github.com/transferwise/neptune-web/pull/836)

## 🖼 Context

This PR aims to fix up a few things, but at the moment I haven't done any tests since I'd like to open it more for a discussion around the approach I've taken (I was planning on doing some exploration and opening a thread but then just decided to continue). 

https://transferwise.atlassian.net/browse/DS-555
https://transferwise.atlassian.net/browse/DS-864

## 🚀 Changes

#### To fix: https://transferwise.atlassian.net/browse/DS-864

Changes our check for the `groupSeparator` to use 10k instead of 1k when trying to get the thousand delimiter. It seems `es-ES` doesn't comma separate `1000` as a value, but does separate `10000`. Updating this check to use `10000` & get the delimiter off the third character fixes the issue and doesn't seem to negatively affect a few of the other locales I tested.

Playing with values in the console to visualise it:

<img width="245" alt="Screenshot 2021-03-05 at 17 18 54" src="https://user-images.githubusercontent.com/52408757/110150800-92d7f800-7dd7-11eb-8900-2794ffef9885.png">

#### To fix: https://transferwise.atlassian.net/browse/DS-555

This is the part of the PR I'm questioning the most. We want to stop users from inputting text values to prevent values like `$1000` since they won't trigger amount `onAmountChange` and customers can get confused as to why the quote isn't updating. 

I can basically think of two main approaches to this: 

1. Prevent user input of unwanted stuff `onKeyDown` before the change fires
2. Set the parsed value to state in `onChange`

I decided to go with the first one since the second approach would require us to store/reset the caret position since otherwise it would jump to the end of the input on each change. The annoying (but also positive I guess?) thing about the first approach is that it requires us to very explicitly say what we'll accept. As you can see, the list is already pretty big just to support a few ways of interacting with the input like selecting all, using arrow keys, etc. so I'm worried this might be too prohibitive an approach. I'm also not sure what impact this will have on accessibility. But, that's what this PR is mostly for, to discuss the approach!

#### To do an entirely unrelated thing

I've added a forwardRef to let us pass a `ref` into the actual input DOM node. It works fine but reads a bit messy because it's a class component so I cant add it to the actual declaration and need to re-export `Size` on the `forwardRef`. I'm guessing you guys might want this either formatted a different way or added with a different approach, just let me know (pretty please don't make me refactor the entire thing to a function component)!

## 🤔 Considerations

## ✅ Checklist

- [ ] Make PR title meaningful and follow [the commit lint format](https://github.com/transferwise/neptune-web/blob/master/CONTRIBUTING.md#versioning-and-commit-lint) (it will appear in the changelog)
- [ ] Changes are tested and all tests pass
- [ ] Changes meet [accessibility standards](https://github.com/transferwise/neptune-web/blob/main/ACCESSIBILITY.md) and there are no violations in the console
- [ ] Changes work in all supported browsers (don't forget IE11)
- [ ] You've updated the documentation if necessary

2021-04-30 11:58 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/currencyFormatting.spec.js
> +    ['asda', NaN],
shall we return 0 if parsed value is NaN ?  means; shall we

keep the existing value when user pastes string without any number (`asda`);
or replace existing value with 0

2021-04-30 14:48 UTC, dozortsev reviewed
I guess this PR closes https://github.com/transferwise/neptune-web/pull/836 right?

cc @fergusjordantw

2021-05-06 08:06 UTC, andreapiras commented on packages/components/src/moneyInput/MoneyInput.js
> +      keyCode === keyCodes.BACKSPACE ||
Hey can we try to reuse this util to verify the key? https://github.com/transferwise/neptune-web/blob/main/packages/validation/src/event-validators/isKey.js

2021-05-06 08:06 UTC, andreapiras commented on packages/components/src/moneyInput/MoneyInput.js
> +      keyCode === keyCodes.BACKSPACE ||
I should put a comment in the keycodes file to deprecate

2021-05-06 08:14 UTC, andreapiras commented on packages/components/src/moneyInput/MoneyInput.js
> +    if (!this.isInputAllowedForKeyEvent(event)) {
I am a bit confused, are we trying to allow only digits here?. If that's the case can we just not use a regular expression to filter event.target.value and remove isInputAllowedForKeyEvent completely?

2021-05-06 08:26 UTC, andreapiras commented on packages/components/src/moneyInput/MoneyInput.js
> +    if (!Number.isNaN(parsed)) {
You can use isNumber from @transferwise/neptune-validation

2021-05-06 08:26 UTC, andreapiras commented on packages/components/src/moneyInput/MoneyInput.js
> +    const isNumberKey = !Number.isNaN(parseInt(key, 10));
You can use isNumber from @transferwise/neptune-validation

2021-05-06 08:27 UTC, andreapiras commented on packages/components/src/moneyInput/MoneyInput.js
> +      : parseAmount(paste, this.props.selectedCurrency.currency, this.locale);
Can we try and reuse this https://github.com/transferwise/formatting/blob/master/src/currency/currency.ts#L57

2021-05-06 08:39 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/MoneyInput.js
> +      : parseAmount(paste, this.props.selectedCurrency.currency, this.locale);
formatAmount returns string with group separator. ( ie: 123456 => 123,456) , however parseAmount returns valid float so consumer safely use it.

2021-05-06 17:22 UTC, fergusjordantw commented on packages/components/src/moneyInput/MoneyInput.js
> +      : parseAmount(paste, this.props.selectedCurrency.currency, this.locale);
I think this should more closely align with how `onAmountChange` works. We should be setting the state to be the "money input value" and then calling `props.onAmountChange` with the parsed float. For paste we should just be stripping out unwanted characters. So if I paste in 1,000.12, I don't think it should reformat it to 1000.12. 

onAmountChange stores the user inputted value in state as `formattedAmount` and calls `props.onAmountChange` with the parsed float. I don't think this should deviate from that, the only thing we want to do here is make sure that the user inputted value is only valid characters (decimals, commas, digits).

2021-05-06 17:22 UTC, fergusjordantw commented on packages/components/src/moneyInput/MoneyInput.js
> +  isInputAllowedForKeyEvent = (event) => {
Missing tests for all of this. Can we write some proper integration tests with RTL to test all of this?

2021-05-07 08:27 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/MoneyInput.js
> +      : parseAmount(paste, this.props.selectedCurrency.currency, this.locale);
When we talked in our last meeting, we aggreed that on paste, everything (including group separator) will be removed. and only digits and decimal separator will stay. did you remember ? @fergusjordantw @helendurranttw

2021-05-07 08:31 UTC, fergusjordantw commented on packages/components/src/moneyInput/MoneyInput.js
> +      : parseAmount(paste, this.props.selectedCurrency.currency, this.locale);
I don't remember that specifically, next time lets write down decisions from the meeting. @helendurranttw can you confirm that's what we want?

2021-05-10 09:08 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/MoneyInput.js
> +  isInputAllowedForKeyEvent = (event) => {
done

2021-05-10 09:22 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/MoneyInput.js
> +    if (!Number.isNaN(parsed)) {
done

2021-05-10 11:47 UTC, andreapiras commented on packages/components/src/moneyInput/MoneyInput.js
> +      keyCode === keyCodes.BACKSPACE ||
Don't worry ignore my comment is was an optional change anyway

2021-05-10 15:03 UTC, helendurranttw commented on packages/components/src/moneyInput/MoneyInput.js
> +      keyCode === keyCodes.COMMA ||
keyCodes are actually [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), so we've been started moving towards [key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key).

We have a similar file of key mappings to the one we have of keyCodes.

I think there are probably a couple you're missing here. `delete` springs to mind, but I think there is also a `clear` button on some keyboards that might be helpful. Possibly also `home` and `end`?

Maybe you could keep a whitelist and then check if the value is in the list, rather than extending this or statement?

2021-05-10 15:09 UTC, helendurranttw commented on packages/components/src/moneyInput/MoneyInput.js
> +      : parseAmount(paste, this.props.selectedCurrency.currency, this.locale);
As per our discussion on Slack, this is the expected behaviour:

**On keypress**
* prevent them from typing anything except numbers, the decimal separator or group separator

**On blur**
* remove invalid characters (e.g. duplicate decimal separators, group separators) and round to 2dp
* format the number using group separators

**On paste**
* remove all characters except numbers and the first decimal separator

I don't think you need to round on paste, since you're going to round on blur.

2021-05-10 15:15 UTC, helendurranttw commented on packages/components/src/moneyInput/currencyFormatting.spec.js
> +    ['asda', NaN],
I think we should leave whatever was there before

2021-05-10 15:20 UTC, helendurranttw commented on packages/components/src/moneyInput/MoneyInput.js
> +      : parseAmount(paste, this.props.selectedCurrency.currency, this.locale);
I think there is some value in matching what we allow the user to type and what we accept on paste. So for example, if the user can type this

123.456 (which will be rounded to 123.46 on blur)
123.45.67 (which will be truncated to 123.45 on blur)

We could allow the same on paste:

$123.456 => 123.456 (on paste) => 123.46 (on blur)
$123.45.67 => 123.45.67 (on paste) => 123.45 (on blur)

This might feel more predictable, since it mimics the behaviour of the input when typing. That said, if we're going to soon limit the user from typing things like duplicate decimal separators.. maybe there's no point 😅

2021-05-11 08:11 UTC, helendurranttw commented on packages/components/src/moneyInput/MoneyInput.js
> +      keyCode === keyCodes.COMMA ||
So we're moving key validation to neptune validation (the package called validation in the neptune web monorepo). You can see the map of existing keys in `common/keyMap.js`. Once you've added the new keys you want to support in there, you can use [this util](https://github.com/transferwise/neptune-web/blob/main/packages/validation/src/event-validators/isKey.js) to check whether the key pressed is one of your list.

2021-05-11 08:41 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/currencyFormatting.spec.js
> +    ['asda', NaN],
before, there was no logic on paste, this is a new thing

2021-05-14 09:59 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/MoneyInput.js
> +      keyCode === keyCodes.COMMA ||
there is an update needed in order to use isKey, right? because not all keys are there

2021-05-17 08:37 UTC, helendurranttw commented on packages/components/src/moneyInput/MoneyInput.js
> +      keyCode === keyCodes.COMMA ||
Yeah, you'll need to add them. Once you've done that you should be able to remove your use of keyCodes :)

2021-05-18 08:46 UTC, fergusjordantw commented on packages/components/src/moneyInput/MoneyInput.spec.js
> +      ['±!@#$^*_+?><,', ''],
I think this should really include some examples of not just numbers being allowed but also decimals and commas

2021-05-18 08:46 UTC, fergusjordantw commented on packages/components/src/moneyInput/MoneyInput.spec.js
> +      numberFormatting.formatAmount = jest.fn((num) => num);
Why do we need to mock formatAmount? Would it be possible to do a `jest.requireActual()` here to bypass the above mock so that we can test the entire integration?

2021-05-18 09:02 UTC, helendurranttw commented on packages/components/src/moneyInput/MoneyInput.js
> +      isKey({ keyType: key, event }) ||
This isn't quite right. The idea of this utility is to check to see if the event is a key you already know about. For example:

```
const { TAB, ESCAPE } = Key;

isKey({ keyType: TAB, event })
```

At the moment the key map only supports checking for space, tab, enter and escape. You probably don't want to support spaces, though I guess the others are fine.

2021-05-18 09:08 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/MoneyInput.js
> +      isKey({ keyType: key, event }) ||
btw isKey doesn’t support space right now, because at keyMap file, it’s key is SPACE  but it should be ' '
like this;
export const keyMap = {
  [' ']: { key: [' ', 'Spacebar'], keyCode: 32 },

I'll remove SPACE from here anyways 👍

2021-05-18 09:32 UTC, helendurranttw commented on packages/components/src/moneyInput/currencyFormatting.spec.js
> +    ['asda', NaN],
Right, I meant keep the existing value.

2021-05-18 14:54 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/MoneyInput.spec.js
> +      ['±!@#$^*_+?><,', ''],
there is an issue with testing library, COMMA and DOT keyCodes are different, and this causes the problem, I found the bug report at [testing-library](https://github.com/testing-library/user-event/issues/456) , it’s resolved at v13, however at neptune components testing library version is v11,

TLDR;
cant add the test entered  134,ada3  => resolved 134,3

from test:
```
console.log
    { keyCode: 44, key: ',', allowed: false }
  console.log:
    { keyCode: 46, key: '.', allowed: false }
```

2021-05-21 16:29 UTC, fergusjordantw commented on packages/components/src/moneyInput/MoneyInput.js
> +      metaKey ||
Can we test this on windows? I know this works for the command key on mac but we need to make sure we aren't removing the ability to paste. Might need to include ctrlKey here

2021-05-24 11:14 UTC, arikanmstf-tw commented on packages/components/src/moneyInput/MoneyInput.js
> +      metaKey ||
very true. added it

2021-05-27 10:09 UTC, helendurranttw approved these changes

2021-05-27 10:41 UTC, fergusjordantw requested changes
When pasting `100.000,12` into it when the locale is es (`.` being the separator, `,` being the decimal place) it parses it on blur to be `10.000.012`. So instead of sending `100,000.12`, we’re now sending `10,000,012.00` (examples with English locale)

2021-05-28 09:35 UTC, arikanmstf-tw commented
> When pasting `100.000,12` into it when the locale is es (`.` being the separator, `,` being the decimal place) it parses it on blur to be `10.000.012`. So instead of sending `100,000.12`, we’re now sending `10,000,012.00` (examples with English locale)

found the issue `this.state.locale stays as `en-GB` even when props changed

2021-06-02 12:02 UTC, fergusjordantw approved these changes

2021-06-02 12:35 UTC, helendurranttw approved these changes
🎉

2021-06-02 13:59 UTC, merged